CREATE TABLE public.dms_plants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL,
  plant_name text NOT NULL,
  location text,
  is_active boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.dms_plants ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read dms_plants" ON public.dms_plants FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert dms_plants" ON public.dms_plants FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update dms_plants" ON public.dms_plants FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can delete dms_plants" ON public.dms_plants FOR DELETE TO authenticated USING (true);

INSERT INTO public.dms_plants (code, plant_name, location, display_order) VALUES
('A001','Accommodation/Office Buildings Kaz','KAZ',1),
('A002','Accommodation/Office Buildings Umm Qasr','UQ',2),
('A003','Accommodation/Office Buildings Ar Ratawi','AR',3),
('A004','Office Building for Umm Qasr Storage Terminal','UQ',4),
('A005','Office Building for Umm Qasr Marine Terminal','UQ',5),
('A006','Office Building for North Rumaila','NR',6),
('B001','Umm Qasr Marine Terminal ERB','UQ',7),
('B002','West Qurna Plant ERB','WQ',8),
('B003','South Rumaila Plant ERB','SR',9),
('B004','Zubair Plant ERB','ZU',10),
('B005','Umm Qasr Storage Terminal ERB','UQ',11),
('B006','North Rumaila NGL Plant ERB','NR',12),
('B007','Khor Al Zubair Plant ERB','KAZ',13),
('C000','Multi Compressor Stations','Other',14),
('C001','North Rumaila CS1','NR',15),
('C002','North Rumaila CS2','NR',16),
('C003','North Rumaila CS3','NR',17),
('C004','North Rumaila CS4','NR',18),
('C005','North Rumaila CS5','NR',19),
('C006','South Rumaila CS Central (Markazia)','SR',20),
('C007','South Rumaila CS Janubiyah','SR',21),
('C008','South Rumaila CS Quarainat Mishrif','SR',22),
('C009','South Rumaila CS Quarainat','SR',23),
('C010','South Rumaila CS Ratqa','SR',24),
('C011','South Rumaila CS Rutka','SR',25),
('C012','South Rumaila CS Shamiyah','SR',26),
('C013','West Qurna CS6','WQ',27),
('C014','West Qurna CS7','WQ',28),
('C015','West Qurna CS8 TEG Unit','WQ',29),
('C016','Zubair Hammar','ZU',30),
('C017','Zubair Hammar Mishrif','ZU',31),
('C018','Zubair Rafidiyah','ZU',32),
('C019','Zubair Safwan','ZU',33),
('C020','Zubair Central','ZU',34),
('C021','Zubair Mishrif','ZU',35),
('C022','North Rumaila NIDS','NR',36),
('C023','North Rumaila SIDS','NR',37),
('C024','Zubair DS Zubair AZ','ZU',38),
('C025','West Qurna Central Compressor','WQ',39),
('C026','North Rumaila Compressor Station NCS2','NR',40),
('C027','North Rumaila Compressor Station NCS5','NR',41),
('C028','Qurainat Compressor Station CCS','SR',42),
('C029','Majnoon Sour Compressor Station','ISGP',43),
('C030','North Rumaila Compressor Station NCS4','NR',44),
('C031','Iraq Compressor Station','AR',45),
('C032','South Rumaila - Qurainat/Shamiya Mishrif Compression and Dehydration','SR',46),
('C033','Hammar Mishrif New Compression Station','ZU',47),
('C034','Qurainat Temporary Compressor Station','SR',48),
('D001','Hammar Dehydration Facility','ZU',49),
('D002','West Qurna 2 Lukoil Plant','WQ',50),
('D003','Tuba DS','TL',51),
('E001','North Rumaila Power Plant','NR',52),
('E002','Khor Al Zubair Power Plant','KAZ',53),
('G000','General','ISGP',54),
('G001','Not used at this time','ISGP',55),
('G002','General / Pan-Project Identifier','ISGP',56),
('L001','Offshore Liquefaction Unit','ISGP',57),
('L002','LNG Supply Pipeline','ISGP',58),
('L003','LNG Plant','ISGP',59),
('N001','North Rumaila NGL','NR',60),
('N002','GTU','Other',61),
('N003','Khor Al Zubair Gas Plant','KAZ',62),
('N004','BNGL Plant','AR',63),
('N099','Iraqi Compressor Station North Rumaila (3rd Party)','Other',64),
('P001','Pipeline System General','ISGP',65),
('P107','NRCS4 to NRNGL 32" Pipeline','NR',66),
('P108','NRCS4 to NRNGL 24" Pipeline','NR',67),
('P701','BNGL to KAZ 20" Broadcut Line','Other',68),
('P702','NR Export 30" Line to BNGL','Other',69),
('P703','Iraq Compressor Station Export 30" Line','Other',70),
('P704','Al-Hukhal WPS 6" Raw water Line to BNGL','Other',71),
('PL01','All Pipelines','Other',72),
('S001','Umm Qasr Receiving Terminal','UQ',73),
('S002','Umm Qasr Storage Terminal','UQ',74),
('S003','Umm Qasr Marine Terminal','UQ',75),
('S004','Umm Qasr New Expansion Work','UQ',76),
('S005','Offshore FLNG','Other',77),
('U001','Umm Qasr Area','UQ',78),
('U002','West Qurna Area','WQ',79),
('U003','Rumaila Area','Other',80),
('U004','Zubair Area','ZU',81),
('W001','Water Intake Station NR NGL','NR',82);