
CREATE TABLE public.dms_originators (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  code TEXT NOT NULL,
  description TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.dms_originators ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated read access on dms_originators" ON public.dms_originators FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert access on dms_originators" ON public.dms_originators FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update access on dms_originators" ON public.dms_originators FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated delete access on dms_originators" ON public.dms_originators FOR DELETE TO authenticated USING (true);

INSERT INTO public.dms_originators (code, description, display_order) VALUES
('AACO','Al-Nabaa Al-Yaqeen Company (NYCO Group)',1),
('AAJN','Alaat Al Jnoup',2),
('AAMF','ABR Al Manara for General Trading',3),
('AASC','AL-Ahleia Switchgear Company KSCC',4),
('ABB','ABB SpA',5),
('ABBG','ABB Industries (CPECC Legacy POs Only)',6),
('ABBI','ABB Industries FZE',7),
('ABBR','ABB S.R.O.',8),
('ABC','Al Barih Company',9),
('ABCO','Al Bathera Communications',10),
('ABJE','ABJ Engineering & Contracting Co. KSC',11),
('ACCM','Al Nabooda Interiors LLC',12),
('ACES','Arab Centre for Engineering Studies',13),
('ACMT','Atlas Copco Mafi-Trench Company LLC',14),
('ADAL','Adwaa ALFayha Co',15),
('ADEC','Al Dhafra Specialized Equipment Co. LLC',16),
('AEBA','Al-Ebtida Co',17),
('AEC','AECOM',18),
('AESB','Agricultural Engineers Syndicate Basra',19),
('AESC','Alfa Engineering Soc. Coop.',20),
('AETL','Andrea Engineering Tests Laboratory',21),
('AFCO','Afcom Infrastructure Ltd',22),
('AGGR','Aggreko Middle East Limited',23),
('AHCF','AHI Carrier FZC',24),
('AIMS','Aim System General Trading LLC',25),
('AJAL','AJAEB AL Mass for Electrical',26),
('AKTL','Atkins Ltd',27),
('AKTO','AKT Oil Services',28),
('ALBI','Al-Bilal',29),
('ALBU','Al-Burhan Group',30),
('ALDA','Al Dar International Co',31),
('ALDE','Alderly FZE',32),
('ALDI','Almonte Diamond PTY Ltd',33),
('ALFA','Alfa Engineering',34),
('ALHI','Al-hillal Company',35),
('ALIN','Almeer Industries',36),
('ALJE','Al Juhd Engineering',37),
('ALM','Almco Ltd Baghdad',38),
('ALMA','Al Mazaween Co',39),
('ALNA','Al Namarek Ceramic & Construction Materials FZE',40),
('ALNU','Al Nuha Company',41),
('ALS','Applied Language Solutions',42),
('ALSAF','Al Safsafa Mine Action Company',43),
('ALTH','Al-Thuraya',44),
('ALUC','Alucor Ltd',45),
('ALUS','Al Usool General Trading Co',46),
('ALVG','ALCO Valves Group Ltd',47),
('ALYAM','Al Yamama Engineering',48),
('ALZA','Al-Zaitoon Co for Oil Services',49),
('AMBS','Al Mubdee Scaffolding LLC',50),
('AMEC','AMEC',51),
('AMEI','Ameridrives International',52),
('AMLT','ALOFT MIDDLE EAST LAB INSTRUMENTS TRADING LLC',53),
('AMTS','Al Majal Technical Services .JV with Sulzer',54),
('ANAS','Ang Automation Solutions FZCO',55),
('ANIX','Anixter Middle East FZE',56),
('ANWA','Anwar Al Ganat Al Alamiya FZCO',57),
('ANWS','Anwar Soura',58),
('APCO','APCON Construction Industry',59),
('APRO','APRO Industrie SAS',60),
('AQA','Aquateam',61),
('ARAK','Al Rubat Al Kabeer Civil and Piling Works',62),
('ARCH','Archilli',63),
('ARGD','Applus RTD Gulf DMCC',64),
('ARIL','Arabian Industries LLC (GCC Branch)',65),
('ARIN','ARMSTRONG INTERNATIONAL PVT LTD',66),
('AROI','Arabian Industries',67),
('ARPS','Arabian Pipeline Supply FZCO',68),
('ARROW','Arrow',69),
('ARUP','Ove Arup',70),
('ASC','Al Sahamara',71),
('ASCO','ASCO Filtri SPA',72),
('ASH','Al Sabbah for General Services (SES)',73),
('ASHC','Ashcroft Instruments GMBH',74),
('ASOF','Ali & Sons Oil-Field Supplies & Services Company',75),
('ASSC','AS Schneider',76),
('ASTE','Abu Saeed Trading Co. LLC',77),
('ASTG','Hafet Electrical LLC',78),
('ATCO','Atlas Copco Middle East FZE',79),
('ATEC','Applied Corrosion Technology FZE',80),
('ATLA','Atlas Copco Services Middle-East (Only for NCS2/4 project)',81),
('ATRIC','ATTRIC Limited',82),
('ATSI','Australia Technical Services International DMCC',83),
('AUM','AUM International FZE',84),
('AUMI','AUM International (CPECC Legacy POs Only)',85),
('AUSE','Al Usool Engineering Services (CPECC Legacy POs Only)',86),
('AUSY','Autochim Systems (Worley Parsons POs)',87),
('AUTO','Autochim Systems (Exterran/Technip POs)',88),
('AXEN','Axens',89),
('BACL','Basrah Construction Laboratory',90),
('BADU','Bilad Al Duha',91),
('BAFI','Barton Firtop Engineering Co Ltd',92),
('BAG','Baghdad Co.',93),
('BAHU','Baker Hughes',94),
('BAKO','Bauer Kompressoren Gmbh',95),
('BAOC','Basrah Operations Command',96),
('BART','Bartec Middle East FZE',97),
('BAU','Basrah University',98),
('BEBA','British Embassy Baghdad',99),
('BETV','Bettis Valves',100),
('BEZE','Beijing Zehua Chemical',101),
('BFSL','BS&B Flamesat Ltd',102),
('BGC','Basra Gas Company',103),
('BGOC','Baghdad Operation Command',104),
('BHBR','Bhatia Brothers FZE',105),
('BITR','Bibby Transmission Ltd',106),
('BJNG','Bejiing Eastern Dragon Petro Tech Ltd',107),
('BLGO','Black Gold Consulting FZ LLC',108),
('BLKP','Brot Laboratories/Kema Proser',109),
('BMEF','Baosteel Middle East FZE',110),
('BMET','Budenberg Middle East Trading',111),
('BNCO','Basra Investment Commission',112),
('BOC','Basrah Oil Company',113),
('BONN','Bonney Forge',114),
('BPC','Basrah Provincial Council',115),
('BRAB','Berger Abam',116),
('BREE','Breeze Air',117),
('BRME','Brendan Meehan Controls',118),
('BRUL','Bracewell (UK) LLP',119),
('BSST','Bin Sari Specialized Technologies',120),
('BUI','Buitendijk Techniek B.V.',121),
('BUVE','Bureau Veritas',122),
('CAEN','Cabalera Engineering FZE',123),
('CAIC','Cameron International Corporation',124),
('CAMC','Communication and Media Commission',125),
('CAME','Caltrols Middle East FZCO',126),
('CAPA','Carpenter & Paterson',127),
('CAPE','Cape Regional Services DMCC',128),
('CATO','Catobo Technical Services',129),
('CBOI','Central Bank of Iraq',130),
('CEBO','Cesare Boneti',131),
('CEEL','CEG Elettronica Industriale SPA',132),
('CEMP','CEMP SRL',133),
('CGGV','CGGVeritas',134),
('CGII','Consulate General of Iraq India',135),
('CGIKL','Consulate General of Iraq Kuala Lumpur Malaysia',136),
('CGINL','Consulate General of Iraq Netherlands',137),
('CGIO','Consulate General of Iraq Oman',138),
('CGIQ','Consulate General of Iraq Doha Qatar',139),
('CGIS','Consulate General of Iraq Sweden',140),
('CGIUK','Consulate General of Iraq United Kingdom',141),
('CGOI','Consulate General of Iraq UAE',142),
('CH2M','CH2M Hill',143),
('CHUK','Chalmit UK',144),
('CLI','Core Laboratories International BV',145),
('COAT','CO-AT Marine Ltd',146),
('COCH','Cooper Crouse-Hindus LLC',147),
('COF','Coffey Environmental Consultants',148),
('COGU','Cochrane Gulf FZE',149),
('COIN','Cooper Industries',150),
('COME','Controls Middle East',151),
('COMI','Commission of Integrity',152),
('COMN','Commtel Networks FZE',153),
('COMS','Corodex Marine Services',154),
('CONT','Control Distributed Trading FZE',155),
('COSA','Cosasco Middle East FZE',156),
('CPCOM','Contracting and procurement sub committee',157),
('CPEC','China Petroleum Engineering Construction Corporation (CPECC)',158),
('CPEN','Chinese Petroleum Engineering',159),
('CPPB','China Petroleum Pipeline Bureau',160),
('CPPU','CP Pumps & Systems FZE',161),
('CRID','Crosco Integrated Drilling & Well Services Co Ltd',162),
('CRSI','Croscorp International Ltd',163),
('CRVA','Crosby Valves',164),
('CRYO','Fives Cryo Inc',165),
('CSJV','Chiyoda-Saipem JV',166),
('CTI','Core Test Systems Inc',167),
('CTSL','Corrosion Tech Services LLC',168),
('CUME','Cummins Power System - Africa Middle East',169),
('CYC','Chiyoda',170),
('DANE','Danem Engineering Works FZE',171),
('DARI','Dar Ibtikar Al Iraq for General Service and General Trade LLC',172),
('DATL','Dubai Advanced Technology',173),
('DAYA','Dayal Building Material Traders',174),
('DBND','DBN Diamant Systemen BV',175),
('DBNW','DNOW UK Ltd',176),
('DBSO','Digby Brown Solicitors',177),
('DDEC','Dron and Dickson Electromechanical Contracting LLC',178),
('DECO','Delta Controls FZCO',179),
('DEL','Delta Controls FZCO (CPECC Legacy POs Only)',180),
('DELO','Deloitte',181),
('DELT','Delta Controls FZCO (CPECC Legacy POs Only)',182),
('DFAIT','Dept of Foreign Affairs and International trade',183),
('DGI','Diamond Gas Iraq',184),
('DHVI','DHV Valves and Foundry Co. Limited',185),
('DIBM','Delta International Building Materials',186),
('DISN','Distribution Now',187),
('DIXO','Dixon Group Europe Ltd',188),
('DODS','Dodsal Export Pipe Line Contractor',189),
('DORC','Dorce Prefabrik Yapi Ve Insaat Sanayii Ticaret AS',190),
('DRCI','Draka Comteq Iberica SL',191),
('DRES','Dresser International Inc.',192),
('DUVI','Dovianus B.V.',193),
('DWRB','Directorate of Water Resources Basrah',194),
('EBAR','Ebara Pumps Middle East FZE',195),
('EBCO','Ebara Corporation Japan',196),
('EBDR','Endress & Hauser Process Automation',197),
('ECCH','Eaton Cooper Crouse Hinds LLC',198),
('ECOL','Ecolog Integrated Services Solutions',199),
('EDGE','Egden Murray',200),
('EDRA','Draeger Safety UK Ltd',201),
('EEIC','Emirates Electrical & Instrumentation Co LLC',202),
('EEWM','EEW Malaysia SDN BHD',203),
('EGMC','Egyptian Maintenance Company',204),
('EHAU','Endress+Hauser (CPECC Handover)',205),
('EHI','Edgo Holding Limited Iraq',206),
('EIGC','Emirates Industrial Gases Co LLC',207),
('EIL','Ecosystem Intelligence Ltd',208),
('EIPS','IPS Trade BV',209),
('EIS','Emirates Islamic Bank',210),
('ELLI','Elliot Group',211),
('EMA','E.M.A Valves',212),
('EMAS','Emerson Automation Solutions',213),
('EMER','Merpro Limited',214),
('EMFZ','Emerson FZE',215),
('EMPH','Emphor FZCO',216),
('EMPM','Emerson Process Management Srl',217),
('ENHA','Endress + Hauser',218),
('ENI','ENI SpA (Agip)',219),
('ENKA','ENKA (MEI Contractor)',220),
('ENLA','ENLAB Laboratuvar Sistemleri IC',221),
('ERGG','Ergil Group',222),
('ERGR','Ergil Grup Insaat Makine Imalat',223),
('ERIK','Eriks BV',224),
('ERM','ERM',225),
('ERWGS','ERW - Group4Securicor',226),
('ERYL','Ernst & Young (Iraq)',227),
('ESMA','ESMA Industrial Enterprises',228),
('ETSL','Emirates Transformer & Switchgear Limited',229),
('ETT','Ettore Cella Spa',230),
('EURO','Europcorr SRL',231),
('EVMI','Everest Metal Industries L.L.C',232),
('EXEA','Exterran Eastern Hemisphere FZE',233),
('EXHE','Exheat PTE LTD',234),
('EXIN','Extol International FZC',235),
('EXTO','Extol International LLC',236),
('EXTR','Exterran',237),
('FABC','Fabcon Industrial Services FZ LLC',238),
('FABT','Fabtech',239),
('FAHE','Faure Herman',240),
('FBMK','FBM KNM FZCO',241),
('FBSA','Federal Board of Supreme Audit',242),
('FCO','Foreign Commonwealth Office - Basrah',243),
('FCOM','Finance sub committee',244),
('FERFB','Ferofab',245),
('FIBE','Fiber Glass Systems Oman LLC',246),
('FIBR','Fiberspar Corporation',247),
('FICP','Flowserve India Controls PVT Limited',248),
('FIND','Finder Pompe SRL',249),
('FIVE','Five North American Combustion Group',250),
('FLAV','Flowserve Valbart SRL',251),
('FLEX','Flexitallic',252),
('FLGU','Flowserve Gulf FZE',253),
('FLOW','Flowserve (Austria) GmbH',254),
('FLR','Fluor Daniel',255),
('FLUE','Fluenta AS',256),
('FMCT','FMC Technologies',257),
('FOF','Federal Office of Financial Supervision',258),
('FORA','Forrain Srl',259),
('FUG','Fugro',260),
('FUGRO','Fugro ME',261),
('FVA','Fisher Valves',262),
('FWMP','FW Murphy Production Controls',263),
('FZV','Fangzheng Valve Manufacturing Co Ltd',264),
('GADK','Gardner Denver Korea',265),
('GAL','Galaxy Oil FZE',266),
('GAMI','Gami Air Conditioners',267),
('GAOS','Gulf Automation Services & Oilfield Supplies',268),
('GARL','Garlock Pipeline Technologies',269),
('GASCO','GASOS Bin Hamoodah',270),
('GASO','GASOS Bin Hamoodah (CPECC Legacy POs Only)',271),
('GAST','Gastech Process Engg',272),
('GBAC','GBA Corona Inc',273),
('GCC','GCC Services',274),
('GCCG','Gulf Catering Company for General Trade & Contracting',275),
('GCGE','Gulf Commercial Group Engineering Services',276),
('GCM','General Secretaries for the Council of Ministers',277),
('GCPI','General Company for Ports of Iraq',278),
('GCT','General Commission of Taxes',279),
('GED','General Education Directorate of Basrah',280),
('GEET','Gersan Elektrik Ticaret',281),
('GEFW','General Federation of Workers',282),
('GEIC','General Instruments Consortium',283),
('GEII','GE International Iraq',284),
('GEMS','Gems International',285),
('GEN','General',286),
('GENE','Gerab National Enterprises LLC',287),
('GENP','General Electric Nuovo Pignone',288),
('GENS','GE Documents for SCOP Compressors (Legacy Records)',289),
('GESE','GE Sensing EMEA',290),
('GFC','Gas Filling Company',291),
('GIIC','Gulf Inspection International Company',292),
('GLO','Glow Oil Company',293),
('GLSG','Global Strategies Group',294),
('GMMO','Gulf Marine Maintenance & Offshor Services Company - Dubai - LLC',295),
('GNOG','GE Oil & Gas Inc',296),
('GOL','Golder',297),
('GOLF','Globe United FZE',298),
('GOUL','ITT Gould Pumps Inc',299),
('GOVB','Governor of Basrah',300),
('GPTI','Gulf Pipeline Testing & Inspection',301),
('GPTS','Gulf Petroleum Technology Service DMCC',302),
('GRMA','G4s Risk Management',303),
('GRV','GRV Flow-Controls GmbH',304),
('GRVF','GRV Flow-Controls GmbH (CPECC Legacy POs Only)',305),
('GTCL','General Trading and Contracting Ltd',306),
('GTES','General Tech Services LLC',307),
('GTSF','Global Transformers & Switchgears FZCO',308),
('GUCO','Gulf Consult',309),
('GULA','Gulf Laboratories Co WLL',310),
('GULC','Gulf Commercial Group Est',311),
('GULF','Gulf Radiant Electricals Trading LLC',312),
('GULS','Gulf Star for Tech. Information and General Contracting Co.Ltd',313),
('GXD','GXD Supply Co',314),
('HALC','Halcrow',315),
('HALG','Habtoor Leighton Group',316),
('HALI','Halliburton',317),
('HAVE','Haven Fire & Safety LLC',318),
('HBAB','Hibba Al Basrah',319),
('HCAH','Hazim Challub Al-Hassani and Partner Company',320),
('HCGB','Hhazim Challob Group Basra Iraq',321),
('HDPE','HDPE Piping Materials',322),
('HUGH','Hughes Safety Showers',323),
('HYEL','Hyundai Electric',324),
('ICML','International Cable Management Limited',325),
('ICON','Iraqi Council of Representatives',326),
('IDMC','Impresub Diving and Marine Contractor SRL',327),
('IEL','Inter Equipment Co Ltd',328),
('IGCC','Iraq Gates Contracting Company',329),
('ILSH','Ilshin Valve Co Ltd',330),
('IMMB','Immigration Department Basra Iraq',331),
('IMSC','Industrie Mecchaniche Scardellato',332),
('IMV','Imtech Vonk B.V',333),
('INAU','Intra Automation',334),
('INCH','Intertech UAE',335),
('INDE','International Development Company',336),
('INFC','International Finance Corporation',337),
('INPI','International Pipeline Production',338),
('INRA','Ingersoll Rand Co. Ltd',339),
('INSP','Intergen SPA',340),
('INTE','Intech Process Automation',341),
('INVS','Invention Steel Industries LLC',342),
('IRAT','Iratrack (Cat)',343),
('IRNS','Iraqi National Security',344),
('IRPO','Iraq Police',345),
('IRSR','Iraqi Radioactive Sources Regulatory Authority (IRSRA)',346),
('IRST','Iraq Star FZE',347),
('IRTE','Iraq Technology for Advanced Energy',348),
('ISCO','Information Security Clearness Office (Basrah)',349),
('ITRC','International Trading Circle',350),
('JAME','James Walker Mooreflex Ltd (UK)',351),
('JAMS','James Walker Mooreflex Middle East FZE',352),
('JBAR','J. Barnsley Cranes Ltd',353),
('JCVA','JC Valvulas (ME) FZC',354),
('JIST','Jiangsu Sunpower Technology Company',355),
('JOHN','Johnson Matthey Catalysts',356),
('JORD','Jord International PTY Ltd',357),
('JPA','J&P-Avax SA',358),
('JWML','James Walker Mooreflex Ltd.(CPECC Purchase Orders only)',359),
('JZHC','John Zink Hamworthy Combustion S.r.l.',360),
('KADD','Kaddas Oilfield Services and Trading Co',361),
('KAES','Kaeser Kompressoren GMBH',362),
('KALE','Kanon Loading Equipment BV',363),
('KANE','Kanoo Energy LLC',364),
('KBR','Kellogg Brown Root',365),
('KECI','Kec International LTD',366),
('KEI','Kuwait Energy Iraq Ltd',367),
('KELV','Kelvion Fze',368),
('KESS','Kessab Steel LLC',369),
('KLYA','KL YAPI Celik Imalat',370),
('KNOW','Knowsley SK Ltd',371),
('KOCH','Koch Industry',372),
('KRME','Krohne Middle East',373),
('KSBM','KSB Middle East FZE',374),
('KTSS','Kelvion Thermal Solutions S.A.S',375),
('LDCM','Local Development Committee',376),
('LEGV','Leser Germany Vide',377),
('LESE','Leser GmbH & Co. KG (Cabalera Engineering FZC)',378),
('LFFG','LFF Glamal Ltd',379),
('LHSC','Ex-Machinery / LHS Consultants B.V.',380),
('LIMI','Limitless International Corp',381),
('LINK','Link Middle East Ltd',382),
('LISE','Lisega India Private Ltd',383),
('LLOY','Lloyds Engineering Co. LLC',384),
('LMEL','Lukoil Middleast Ltd',385),
('LOAU','Loop Automation',386),
('LOFF','London Fittings and Flanges Ltd',387),
('LOLE','Lootha Lemmens LLC',388),
('LSC','LinScan',389),
('LTVL','L&T Valves Limited',390),
('MAAB','Mohamed Abdulraham Al Bahar',391),
('MACL','John Maclean & Sons Electrical (Dingwall) Limited',392),
('MAGN','Magnetrol Intl (CPECC Legacy POs Only)',393),
('MAIS','Masseera Industrial Switchgear FZE',394),
('MANI','Mansoori Industrial Supply',395),
('MAR','Maritime Agencies Company',396),
('MARE','Marelli Motori SPA',397),
('MARI','Marimatech AS',398),
('MAS','Masco',399),
('MASCO','Masco Epc',400),
('MASI','Masibus Automation And Instrumentation FZC',401),
('MASS','Masseera Electrical Switchgear',402),
('MAST','Mabani Steel LLC',403),
('MATE','Matec Group S.R.L',404),
('MCO','Ministry of Communication',405),
('MD','Mott MacDonald',406),
('MEDR','Metal Deployee Resistor',407),
('MEGA','Megan Services DMCC',408),
('MEMB','Membrane Technology',409),
('MEOS','MEOS Co. LLC',410),
('MESL','Megatech Control Systems LLC',411),
('META','Metalfab Middle East FZ LLC',412),
('METE','Mechatest',413),
('METI','METITO (Overseas) Ltd',414),
('MFCC','MFC Cargo Container Concept LLC',415),
('MFVI','Master FLO Value inc',416),
('MGL','Magnetrol-Jupiter',417),
('MHAM','Al Maham Engineering Projects Co. LTD',418),
('MHI','Mitsubishi Heavy Industries',419),
('MIDF','MI Drilling Fluids',420),
('MILT','Milton Roy',421),
('MIM','Ministry of Industry and Minerals',422),
('MINC','Minco India Flow Elements Pvt LTD',423),
('MIOJ','Ministry of Justice',424),
('MLEG','Maclean Electrical Group',425),
('MMD','Mott MacDonald',426),
('MMP','Ministry of Municipalities and Public Works',427),
('MMSM','Mutual Marine Services Al Mushtaraka Ltd',428),
('MOE','Ministry of Electricity (Basrah)',429),
('MOEN','Ministry Of Environment',430),
('MOF','Ministry of Finance',431),
('MOH','Ministry of Health (Basrah)',432),
('MOI','Middle Oil Company',433),
('MOIB','Ministry of Interior Baghdad',434),
('MOL','Iraqi Ministry of Labor',435),
('MOND','Mondiale Group PTE LTD',436),
('MOO','Ministry of Oil',437),
('MORR','Morrel International Srl',438),
('MOT','Ministry of Transport',439),
('MOTR','Ministry of Trade',440),
('MOV','Mood Valves',441),
('MRC','Midland Refineries Co.',442),
('MRCG','MRC Global Middle East FZE',443),
('MRCT','MRC Transmark Pte Ltd',444),
('MVPT','MVP Technology G.T.',445),
('MWR','Ministry of Water Resources',446),
('MYCO','Mycom',447),
('NAFF','Naffco Fire Fighting Equipment',448),
('NEET','Next Engineering Equipment Trading',449),
('NEPS','Netzsch Pumpen & Systeme GmbH',450),
('NEST','National Engineering Services & Trading Co. LLC (UAE)',451),
('NETH','Netherlock Safety Systems',452),
('NETZ','Netzsch Pumpen & Systeme GmbH',453),
('NEWA','Neway Flow Control Valves',454),
('NEXUS','Nexus Global Business Solutions',455),
('NFCD','Neway Flow Control DMCC',456),
('NKKK','Nippon Kokan KK',457),
('NOCP','North Oil Company',458),
('NOGC','North Gas Company',459),
('NOV','Novo Fima',460),
('NPGE','Nuovo Pignone Srl',461),
('NTBN','Nvent Thermal Belgium NV',462),
('NUMO','Nuova Mondial Mec Srl',463),
('NUOV','Nuova Giungas Srl',464),
('NURE','Nur Engineering Contracting & Importation',465),
('NVSC','Neway Valve (Suzhou) Company Limited',466),
('NXAN','Nexans Turkiye Endustri',467),
('NYC','Nyco Inspection Company',468),
('OCIS','Oman Cables Industry SAOG',469),
('OFFE','Offshore Engineering',470),
('OFFI','Officine Meccaniche Gallaratesi',471),
('OGAS','Oil and Gas Construction Factory LLC',472),
('OGCS','Oil Gas & Constructions Services',473),
('OIEM','Oil Engineering Middle East LLC',474),
('OIS','Oilserve',475),
('OLV','Olive Group',476),
('OMAN','Oman Cables',477),
('OMBV','OMBV Valves',478),
('OMEG','Omega Engineering FZC',479),
('ONLE','Online Electronics Ltd',480),
('ONLI','Online Cables DMCC',481),
('ONOT','ONO Trading FZCO',482),
('OOSC','OOSC Coating FZC',483),
('OPCO','Oil Pipelines Company',484),
('OPCS','Optilan Communication Systems',485),
('OPD','Oil Products Distribution Company',486),
('OSWA','Oswal Industries Ltd',487),
('PALL','Pal International Sarl',488),
('PANA','Panalpina World Transport Ltd',489),
('PAPU','Patterson Pump Ireland Ltd',490),
('PARS','Parsons',491),
('PCLD','Petroleum contract and Licensing directorate',492),
('PCMM','PCM Middle East FZE',493),
('PCMS','Petrofac for Construction Management Services',494),
('PEC','Petrofac Engineering Construction',495),
('PEIN','Petropipe International ME',496),
('PEN','Pentair Flow Control Middle East',497),
('PENT','Pentair Co',498),
('PERF','Perfect Engineering Fze',499),
('PETJ','Petrojet',500),
('PFF','PFF Middle East Group',501),
('PFFM','PFF Middle East DWC LLC',502),
('PHBW','PHB Weserhutte S.A.U.',503),
('PHME','Phoceenne M.E.',504),
('PIEL','Pielkenrood Projects BV',505),
('PIET','Pietro Fiorentini SPA',506),
('PIL','Petrofac International Limited',507),
('PITEC','Piling Tech',508),
('PIUL','Petrofac International UAE Ltd',509),
('PMAG','Magnetrol International NV',510),
('PMAP','Pharos Marine Automatic Power',511),
('PMM','Prime Minister',512),
('POCA','Powerica Limited',513),
('POIL','Polycab India Limited',514),
('POYRY','Poyry Energy Ltd',515),
('PRAJ','Praj Industries Ltd',516),
('PREK','Prekons Construction Co. Inc.',517),
('PREP','Pressure Products Inc',518),
('PRIM','PRIMIX B.V.',519),
('PRKR','Parker Middle East FZE',520),
('PROC','Procedyne Engineers',521),
('PROE','PRO-C.E.S.S FZE',522),
('PROG','Progetti Europa & Global s.p.a.',523),
('PRPO','Prysmian Powerlink',524),
('PRSY','Process Systems',525),
('PRYS','Prysmian Italy Vide',526),
('PSAL','Pipe Supports Asia Limited',527),
('PSBS','PSB SRL Industrial Valve',528),
('PSFR','PS France',529),
('PUMP','Pump Works',530),
('QWIP','Quality Wire Products Co W.L.L',531),
('RAAR','Rawasi Al Rumailah DMCC',532),
('RAAT','Ratba''a Contracting Company LLC',533),
('RAKO','Ras Al Khaimah Oil Services Energy LLC',534),
('RECO','Redco FZE',535),
('REMB','Rembe GmbH Safety & Control',536),
('RHS','Royal Haskoning',537),
('RISS','Risktek Solutions Ltd',538),
('RITZ','RITZ Instrument Transformers GmbH',539),
('RMEL','R&M Electrical Group Ltd',540),
('RMSN','R&M SN Electrical FZCO',541),
('RMWE','R&M Wholesale Electric LLC',542),
('ROAU','Royaa Al-ufoq',543),
('ROCK','Rockwell Automation LLC',544),
('ROE','Rosemount Emerson Valves',545),
('ROME','Roxtec Middle East FZE',546),
('ROO','Rumaila Operating Organisation',547),
('ROTO','Rotork Middle East FZE',548),
('RPC','Ringstone Petroleum Consultants LLC',549),
('RPVL','RP Valves Ltd',550),
('RSI','Rosemount Valves Inc.',551),
('RSK','RSK',552),
('RSME','R Stahl Middle East FZE',553),
('RSTA','R Stahl Gulf FZCO',554),
('RSTS','Rafiq Sons Technical Services L.L.C.',555),
('RTA','River Transportation Authority',556),
('RUEG','Rueger S.A.',557),
('RUHR','Ruhrpumpen India Pvt Ltd',558),
('SAAB','Sandvik AB',559),
('SABR','Sabre Instrument Valves Ltd',560),
('SABZ','Shell Aberdeen Office',561),
('SADT','Sesco Abu Dhabi Trading LLC',562),
('SAEL','Safety Electrical Group',563),
('SAI','Saipem',564),
('SAIP','Saipem SpA',565),
('SAJ','Sajer Iraq Oil Services',566),
('SAME','SAM Engineering & Trade Co Ltd',567),
('SARC','Sarens Co',568),
('SASB','Shibata Asia Son BHD',569),
('SBLR','Shell Bangalore',570),
('SCEL','Scelerin Heaters LLC',571),
('SCF','State Company of Fertilizers',572),
('SCHLM','Schlumberger Middle East S.A.',573),
('SCIE','Scientechnic LLC',574),
('SCME','Sumitomo Corporation Middle East FZE',575),
('SCOI','SCORE Middle East FZE',576),
('SCOP','Scop',577),
('SCOS','One Surface Schlumberger',578),
('SCR','State Commission for Rodas and Bridges',579),
('SEC','Scheider Electric Company',580),
('SESA','Start Electrical Switchgear Assembly',581),
('SESS','SES Star Trading Est',582),
('SEVE','Severn Valve Solutions FZCO',583),
('SGC','South Gas Company',584),
('SGI','Shell Gas Iraq B.V.',585),
('SGSI','Shell Global Solution International',586),
('SICI','SICIM S.p.A',587),
('SIEA','Siemens Aktiengesellschaft',588),
('SIEL','Siemens LLC',589),
('SIEM','Siemens',590),
('SIEP','SIEP',591),
('SIES','Siemens Sanayi VE',592),
('SIGPL','Shell International Gas & Power Limited',593),
('SING','Sinergia Srl',594),
('SINV','Siraj Naybur Vide',595),
('SIPD','Shell Iraq Petroleum Development',596),
('SIRA','Siraj Naybur Iraq',597),
('SISI','Siemens Singapore',598),
('SKAE','SKA Energy',599),
('SKYL','Sky Light Electric Ware Trading LLC',600),
('SLS','Shenyang Liming Shunda Petrochemical',601),
('SNAFE','Snafee Company Iraq',602),
('SNC','SNC Lavalin',603),
('SNFO','Siraj Naybur for Oilfield Services Abbasiya',604),
('SOA','Southern Area Customs Department',605),
('SOC','South Oil Company',606),
('SOE','Survey Design & Research Institute of ZPEB',607),
('SOFI','SOFIS BV',608),
('SOLA','Solas Marine Services Co. LLC',609),
('SOLM','Solas',610),
('SOMA','Solas Marine Services Est.',611),
('SOMO','State Organization for Marketing of Oil',612),
('SOPD','South Oil Police Directorate',613),
('SOTU','Solar Turbines Incorporated',614),
('SPEC','Specialist Services LLC',615),
('SPET','Spectra Technical Services',616),
('SPGS','Sun Power-Gen System & Service LLC',617),
('SPPP','SPP Pumps Ltd',618),
('SPPR','Specialised Power Products',619),
('SPR','Spriano Milano',620),
('SPTI','Shell P&T',621),
('SRC','Southern Regional Customs Directorate',622),
('SRCD','Southern Region Customs Department',623),
('SRE','South Refineries Company',624),
('SSES','Sirio Sistemi Elettronici SPA',625),
('STAH','Stahl Crane Systems FZE',626),
('STAN','Standard Engineers',627),
('STAS','Shell STASCO',628),
('STAT','Statron Middle East FZCO',629),
('STCO','S & T Corporation',630),
('STEC','Site Technology Ltd. Company',631),
('STEW','Stewart Buchanan Gauges',632),
('STIN','Statron India PVT',633),
('STMT','State co. Maritime Transport',634),
('STR','Strainstall UK Ltd',635),
('STSL','Standard Technical Supply LLC',636),
('SUCE','Sumitomo Corporation Europe Ltd.',637),
('SUIN','Sundyne International',638),
('SULZ','Sulzar Rotating Equipments FZE',639),
('SVIP','Sitindustrie Valvometal - Ital Parts Group Srl',640),
('SWS','Swiss Singapore',641),
('SYNC','Synergy Corporation FZC',642),
('TAAZ','Taaz Construction LLC',643),
('TALI','Talia Deutschland GMBH',644),
('TAME','Tameer Al Janoob Genaral Contract CO',645),
('TAMS','Tai Milano SpA',646),
('TAYL','Taylor Hobson Ltd T/A Solartron ISA',647),
('TCAU','Trouvay & Cauvin Gulf (CPECC POs Only)',648),
('TCN','Technip',649),
('TCOM','Technical sub committee',650),
('TEAI','Teledyne Analytical Instruments',651),
('TECH','Technip International FZC',652),
('TECN','Tecnoforn Industria SRL',653),
('TEGS','Techno Engineering Service Pvt Ltd',654),
('TEIN','Tech International FZC',655),
('TELI','Telinstra FZCO',656),
('TEME','Technical Metal Establishment',657),
('TENO','Technomak Energy International FZC',658),
('TEPO','Termomeccanica Pompe',659),
('TEPS','Technical Parts Establishment',660),
('TESO','Technical Solutions to Industry FZE',661),
('TFSL','Technical Field Services Limited',662),
('THC','Technip-HQC JV',663),
('THCL','Thermo Cables Limited',664),
('THEB','The British Rototherm',665),
('THEP','The Prospects of Engineering Vision',666),
('THER','Thermon Middle East WLL',667),
('THIL','Tuleila Heat Insulation Limited',668),
('THRM','Thermon Middle East WLL (CPECC Legacy POs Only)',669),
('TIVV','TIV Valves Srl',670),
('TMEL','Triplefast Middle East Limited (CPECC Legacy POs Only)',671),
('TMTE','TM Tecnomatic SRL',672),
('TOER','Touma Engineering & Research International',673),
('TRAD','Trizac Abu Dhabi',674),
('TRAN','Tranter India Ltd',675),
('TRCA','Trouvay & Cauvin Gulf BSC (c)',676),
('TRGP','Trans Global Projects',677),
('TRIF','Triplefast Middle East',678),
('TRIP','Triplefast Middle East Limited',679),
('TROU','Trouvay Cauvin Gulf BSC (Exterran POs Only)',680),
('TRVC','Transvac Systems Ltd',681),
('TTIL','Turner & Townsend International LLC',682),
('TURK','Turk Prysmian Kablo Sistemleri A.S.',683),
('TYCF','Tyco Fire and Safety',684),
('TYCO','Tyco Fire and Security UAE LLC',685),
('TYO','Toyo Engineering',686),
('UBS','Ubique Solutions FZ LLE',687),
('UEC','Unaoil',688),
('UGCO','Uni Gas Co',689),
('UKHO','United Kingdom Hydrographic Office',690),
('UMMI','Ummins Arabia Fzco',691),
('UNEC','Una E&C PTE',692),
('UNIG','Unigaz Iraq',693),
('UNLI','Unatrac Ltd',694),
('UNTR','Unatrac International Company Egypt',695),
('URS','URS',696),
('VAIN','Vamoil International FZC',697),
('VALV','Valvitalia s.p.a',698),
('VAMA','Valcon-Matic Pacific Private Limited',699),
('VATE','Valve Technical Services FZE',700),
('VEGA','Vega Technique SAS',701),
('VELA','Velath Engineering International FZC',702),
('VELO1','Velosi (Inspection Outside Iraq)',703),
('VELO2','Velosi (Inspection Inside Iraq)',704),
('VENG','Venandi Global DMCC',705),
('VEOL','Veolia Water Systems (Gulf) FZC',706),
('VIZO','Vizocom FZE',707),
('VJTV','Vijay Tanks & Vessels Ltd.',708),
('VLEE','Van Leeuwen',709),
('VTSA','Vinci Technologies SA',710),
('VULC','Vulcanic UK Ltd',711),
('VVCM','Virgo Valves & Controls [ME] FZE',712),
('WAAR','Waaree ATG Instruments and Control Trading LLC',713),
('WAJD','Wajdi Technical Export',714),
('WASC','Wasco Engineering',715),
('WATE','Wada Technical Export',716),
('WEAT','Weatherford',717),
('WEIR','Weir Flow Control',718),
('WESO','Weir Solutions FZE',719),
('WGEL','Wood Group Engineering Ltd',720),
('WIKA','Wika Middle East FZE',721),
('WOEN','Woodlands Energy Ltd',722),
('WOOD','Woodfield Systems International',723),
('WOP','Worley Parsons',724),
('WPIF','Weir Power & Industrial France',725),
('WQ1F','WQIFOD',726),
('WUXI','Wuxi Jinlong Petrochemical',727),
('YKME','Yokogawa Middle East & Africa B.S.C.',728),
('YOKM','Yokogawa Middle East B.S.C.',729),
('ZABA','Zain Al-Basrah',730),
('ZEEC','Zeeco Inc',731);
