
-- Create dms_document_types table
CREATE TABLE public.dms_document_types (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT NOT NULL,
  document_name TEXT NOT NULL,
  document_description TEXT,
  tier TEXT,
  rlmu TEXT,
  discipline_code TEXT,
  discipline_name TEXT,
  acceptable_status TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.dms_document_types ENABLE ROW LEVEL SECURITY;

-- RLS policies
CREATE POLICY "Authenticated users can view document types"
  ON public.dms_document_types FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert document types"
  ON public.dms_document_types FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update document types"
  ON public.dms_document_types FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated users can delete document types"
  ON public.dms_document_types FOR DELETE TO authenticated USING (true);

-- Seed data from Excel (all rows)
INSERT INTO public.dms_document_types (code, document_name, document_description, tier, rlmu, discipline_code, discipline_name, acceptable_status, display_order) VALUES
('0480', 'Other Agreement', 'Other Agreement', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 1),
('0706', 'Independent Assessment Report', 'External review and assessment of project health that usually includes benchmarking and recommendations from other companies implementing similar work or projects.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 2),
('0709', 'Risk Assessment Report', 'Overall assessment of overall compound technical risk foreseen for the project.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 3),
('0712', 'Social Impact Assessment Report', 'Community Affairs, local content issues, societal effects of project, local business development, etc.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 4),
('0780', 'Other Assessment Report', 'Health check, GAP analysis etc.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 5),
('1905', 'Benchmarking Data', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 6),
('3004', 'Equipment Criticality Rating Report', 'Shows criticality rating of equipment, sparing, maintenance testing and inspection requirements, spare parts requirements etc. Will feed into maintenance reference plan.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 7),
('3180', 'Other Estimate', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 8),
('3311', 'Change Notification', 'An advance notice to another party, e.g. another design department or fabrication facility, that there is going to be a change to a document that has been issued for construction.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 9),
('3322', 'Demonstration Note On Compliance', 'A document that demonstrates that the design meets the Process Safety Basic Requirements (PSBR) of DEM 2 with evidences and references to documents.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 10),
('3341', 'Manpower Histogram', 'Histograms to show current and predicted manpower through project broken down by trade/profession', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 11),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor as requested in contract procedures', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 12),
('3352', 'Organogram', 'Represents an organisation of people, indicating roles and reporting lines in a tree-like structure. May include the names of individuals. Associated with AA only.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 13),
('3366', 'Technical Query', 'Technical Query Includes STQ (Site Technical Query)', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 14),
('4018', 'General Arrangement Diagram', 'A diagram showing the main features and locations of major items. Usually has some dimensions to convey spatial relationships but is generally inadequate for construction.', 'Tier 1', 'RLMU', 'HX', 'HSE&S General', 'ASB, AFC, AFU, AFD', 15),
('4018', 'General Arrangement Diagram', 'A diagram showing the main features and locations of major items. Usually has some dimensions to convey spatial relationships but is generally inadequate for construction.', 'Tier 1', 'RLMU', 'MX', 'Mechanical Other', 'ASB, AFC, AFU, AFD', 16),
('4018', 'General Arrangement Diagram', 'A diagram showing the main features and locations of major items. Usually has some dimensions to convey spatial relationships but is generally inadequate for construction.', 'Tier 1', 'RLMU', 'IN', 'Instrumentation', 'ASB, AFC, AFU, AFD', 17),
('4018', 'General Arrangement Diagram', 'A diagram showing the main features and locations of major items. Usually has some dimensions to convey spatial relationships but is generally inadequate for construction.', 'Tier 1', 'RLMU', 'AA', 'Management & Project Eng', 'ASB, AFC, AFU, AFD', 18),
('4301', 'Action List', 'Includes Punch List.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 19),
('4303', 'Applicable Standards List', 'Provides the lists of Company Standards identified for use as baseline standards for a project.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 20),
('4322', 'Equipment Summary List', 'An extract from a Register that is used as a secondary reference (ie. not the master).', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 21),
('4880', 'Other Manual', 'A document that describes methods of working to be used to accomplish an activity.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 22),
('5206', 'Other Picture', 'Photo or Illustration', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 23),
('5529', 'Project Philosophy', 'Including buildings, access, drainage, corrosion/materials, electrical design, fire and gas, commissioning, isolation, maintenance, operations, earthing, HVAC, metering, process control, well control, utility requirements and design.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 24),
('5706', 'Assurance Plan', 'Quality, compliance, technical, value, cost and schedule assurance.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 25),
('5726', 'Field Development Plan', 'Sub-surface, surface, reservoir management, joint venture partners, high level operations philosophy, high level facilities description, environmental impact, HSE and QA/QC principles.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 26),
('5753', 'Permit Plan', 'Permits and licenses required to allow project work and construction to take place', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 27),
('5759', 'Project Control Plan', 'Throughout the project phases, the project control systems and procedures should be documented in the Project Control Plan PCP.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 28),
('5760', 'Project Execution Plan', 'One of the most important documents on a project, established prior to FEED. The PEP may be as short or as long as warranted by the size and complexity of the project.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 29),
('5768', 'Risk and Opportunity Management Plan', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 30),
('5775', 'Stakeholder Engagement Plan', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 31),
('5778', 'Sustainable Development Plan', 'Community Affairs, local content issues, societal effects of project, local business development, etc.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 32),
('5787', 'Verification Scheme', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 33),
('5798', 'Project Plan', 'Reserved for project wide Discipline Management Plans such as Project QA Plan, Project HSES Plan, Project IM Plan, etc.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 34),
('5800', 'Interface Plan', 'Interface between internal and external parties (esp. between contract scopes).', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 35),
('5806', 'Discipline Delivery Plan', 'A document showing how a particular discipline participates to DCAF controls.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 36),
('5878', 'Gas and Energy Management Plan', 'The Greenhouse Gas and Energy Management Plan (GHGEMP) is the main vehicle for integrating the different aspects of the management process.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 37),
('5880', 'Other Plan', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 38),
('5980', 'Other Strategy', 'Includes Project Execution Strategy (PES).', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 39),
('6003', 'Assurance Procedure', 'Quality, compliance, technical, value, cost and schedule assurance.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 40),
('6006', 'Change Control Procedure', 'Describing how changes through Design, Construction and Commissioning will be managed.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 41),
('6048', 'Communication Procedure', 'Cross discipline, internal and external communication procedure, responsibilities, and governance.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 42),
('6069', 'Interface Procedure', 'Procedures around Interface management activities between internal and external parties.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 43),
('6179', 'Country Regulation Procedures', 'Procedures to develop country regulation specific documents or to submit documents to regulatory authorities.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 44),
('6180', 'Other Procedure', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 45),
('6402', 'Change Proposal', 'A formal document, whose structure and content is defined in the Change Control Procedure.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 46),
('6480', 'Other Proposal', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 47),
('6603', 'Authority Matrix', 'A list or register of people or organisations authorised to perform a range of tasks.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 48),
('6605', 'Change Control Register', 'Audit trail summarising status and outstanding actions associated with all change to originally agreed design.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 49),
('6612', 'Equipment Register', 'Master Tag and Equipment list including all items displayed on the Process Engineering Flow Schemes.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 50),
('6614', 'Laws, Regulations Register', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 51),
('6619', 'Risk, Opportunity Register', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 52),
('6627', 'Interface Register', 'Interface between internal and external parties (esp. between contract scopes).', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 53),
('6680', 'Other Register', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 54),
('6844', 'Economics Study', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 55),
('6926', 'Opportunity Framing Report', 'Workshop, MOM, whitepapers, studies, brainstorm session etc.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 56),
('6944', 'Progress Report', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 57),
('6945', 'Project Closeout Report', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 58),
('7180', 'Other Report', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 59),
('7202', 'Waiver Request', 'Request, approval or rejection for the relaxation of an element of the particular regulatory Code, Standard, Rule or Regulation.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 60),
('7205', 'Technical Deviation Request', 'Request, approval or rejection of changes to a technical specification.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 61),
('7403', 'Design Review Report', 'Verification of a design, based on comparison with standards, constructability, operability, safety, etc.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 62),
('7415', 'Value Assurance Review Report', 'Provides confidence that the opportunity team has done everything necessary to take the decision.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 63),
('7417', 'Lessons Learned Review Report', 'The Lessons Learnt should be captured at the end of each phase while people are still around.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 64),
('7480', 'Other Review Report', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 65),
('7704', 'Basis Of Design', 'Document outlining the basis for the design of the facility and comprising all process design philosophies.', 'Tier 2', NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 66),
('7739', 'Project Specification', 'A technical description of the information on a Project necessary to prepare a +/-10% estimate.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 67),
('7753', 'Terms Of Reference', 'Specifies the scope and details of the activity to which it refers.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 68),
('7772', 'Drafting Specification', 'Rules and Conventions for preparing drawings, including symbol lists, etc.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 69),
('7875', 'Interface Document', 'The information in the interface register, interface diagram and tie-in list are combined in an Interface Document.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 70),
('7877', 'Country Regulation Specific Technical Standard', 'A Specific Technical Standard developed for design and construction of facilities.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 71),
('7878', 'Country Regulation Technical Project Documentation', 'Technical Project Documentation submitted to regulatory authorities for review and approval.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 72),
('7880', 'Other Specification', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 73),
('8203', 'Basis Of Feasibility Study', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 74),
('8211', 'Conceptual Design Feasibility Study', 'Initial screening, feasibility studies, initial estimates, preliminary economics etc.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 75),
('8212', 'Conceptual Engineering Study', 'Workshop, MOM, whitepapers, surface and sub-surface studies, brainstorm session, economics, initial cost estimates, development options', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 76),
('8380', 'Other Study', NULL, NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 77),
('8502', 'Clarification Request', 'Clarification RFI (Clarification Request for Additional Information) at the start of contract or work order.', NULL, NULL, 'AA', 'Management & Project Eng', 'IFI, AFU, AFP, AFT', 78),
('709', 'Risk Assessment Report', 'Overall assessment of overall compound technical risk foreseen for the project.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 79),
('780', 'Other Assessment Report', 'Health check, GAP analysis etc.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 80),
('1580', 'Other Certificate', NULL, NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 81),
('2322', 'Equipment Installation Diagram', 'Installation refers to the mounting, setting, erection, etc. of equipment and accessories.', NULL, NULL, 'BA', 'Construction', 'AFC, AFU, AFD', 82),
('2341', 'Interface Diagram', 'Diagrams showing Interface terminations and hook ups between Contractors', NULL, NULL, 'BA', 'Construction', 'AFC, AFU, AFD', 83),
('2404', 'Construction Diagram', 'Construct is to Erect, Build, or Make (usually) on-site as a responsibility of the project team.', NULL, NULL, 'BA', 'Construction', 'AFC, AFU, AFD', 84),
('2406', 'Constructability Diagram', 'Decomposition of a complex objects/concepts into simpler pieces that make construction feasible.', NULL, NULL, 'BA', 'Construction', 'AFC, AFU, AFD', 85),
('3314', 'Conceptual Design Assumptions For Asset Decommissioning', 'Self Explanatory', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 86),
('3323', 'Technical Note', 'Agreement which describes how an engineering or maintenance issue will be resolved.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 87),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor as requested in contract procedures', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 88),
('3366', 'Technical Query', 'Technical Query Includes STQ (Site Technical Query)', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 89),
('4354', 'Spare Part List', 'Recommended listing of spares to support construction, installation, commissioning, operation or maintenance.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 90),
('4802', 'Commissioning Manual', NULL, NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 91),
('4816', 'Method Statement', NULL, NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 92),
('5503', 'Commissioning Philosophy', 'Commissioning', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 93),
('5537', 'Construction Philosophy / Constructability Review Report', 'Construct is to Erect, Build, or Make (usually) on-site.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 94),
('5711', 'Commissioning and Start-up Plan', 'A plan explaining how commissioning and startup will be accomplished.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 95),
('5736', 'Lifting, Hoisting, Constructability Plan', NULL, NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 96),
('5789', 'Weld Map', 'Outline drawing that usually identifies all welds and relates them to the relevant welding procedure number.', NULL, NULL, 'BA', 'Construction', 'AFC, AFU, AFD', 97),
('5794', 'Workpack', NULL, NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 98),
('5799', 'Commissioning and Start-up Strategy', 'The strategy explaining how commissioning and startup will be accomplished.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 99),
('5801', 'Decommissioning Plan', NULL, NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 100),
('6008', 'Commissioning Procedure', 'Procedure shall include list of spare parts, special tools and utilities required.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 101),
('6064', 'Welding Repair Procedure', NULL, NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 102),
('6065', 'Welding Procedure Specification', 'A specified course of action followed in welding. Includes Welding Procedure Specification WPS.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 103),
('6066', 'Welding Procedure Qualification', 'Describes the parameters used in qualification of Welding Procedures.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 104),
('6070', 'Construction Procedure', 'Construct is to Erect, Build, or Make (usually) on-site.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 105),
('6180', 'Other Procedure', NULL, NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 106),
('7180', 'Other Report', NULL, NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 107),
('7303', 'Requisition', 'A request for service or product initiated by the user or consumer.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 108),
('7739', 'Project Specification', 'A technical description of the information on a Project necessary to prepare a +/-10% estimate.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 109),
('7753', 'Terms Of Reference', 'Specifies the scope and details of the activity to which it refers.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 110),
('7756', 'Construction Specification', 'Construct is to Erect, Build, or Make (usually) on-site.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 111),
('7879', 'Welding And Weld Inspection Specification', 'Define the material types and welding/inspection minimum requirements.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 112),
('7880', 'Other Specification', NULL, NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 113),
('8236', 'Lifting Study', 'Will determine needs for cranes and handling equipment access at design stage.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 114),
('8382', 'Construction Study', 'Construct is to Erect, Build, or Make (usually) on-site.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 115),
('8502', 'Clarification Request', 'Clarification RFI at the start of contract or work order.', NULL, NULL, 'BA', 'Construction', 'IFI, AFU, AFP, AFT', 116),
('1457', 'Completion Certificate', 'A document certifying a commissioning unit has been successfully tested for functionality.', NULL, NULL, 'BC', 'Commissioning', 'IFI, AFU, AFP, AFT', 117),
('4354', 'Spare Part List', 'A list of recommended listing of spares received from vendor/manufacturer.', NULL, NULL, 'BC', 'Commissioning', 'IFI, AFU, AFP, AFT', 118),
('4880', 'Other Manual', 'A document that describes methods of working to be used to accomplish an activity.', NULL, NULL, 'BC', 'Commissioning', 'IFI, AFU, AFP, AFT', 119),
('5680', 'Other Philosophy', 'A document outlining the premise and intent for decisions.', NULL, NULL, 'BC', 'Commissioning', 'IFI, AFU, AFP, AFT', 120),
('5798', 'Project Plan', 'A document capturing key discipline execution plans applicable across the project scope.', NULL, NULL, 'BC', 'Commissioning', 'IFI, AFU, AFP, AFT', 121),
('5799', 'Commissioning And Startup Strategy', 'A document outlining purpose and approach for commissioning and start-up.', NULL, NULL, 'BC', 'Commissioning', 'IFI, AFU, AFP, AFT', 122),
('5980', 'Other Strategy', 'A document outlining the application of a philosophical stance for decisions.', NULL, NULL, 'BC', 'Commissioning', 'IFI, AFU, AFP, AFT', 123),
('6180', 'Other Procedure', 'A document which describes a set of logically sequenced instructions to execute an activity.', NULL, NULL, 'BC', 'Commissioning', 'IFI, AFU, AFP, AFT', 124),
('7770', 'Functional Design Specification', 'A specification that describes the deliverable in terms of form, fit, function, and performance characteristics.', NULL, NULL, 'BC', 'Commissioning', 'IFI, AFU, AFP, AFT', 125),
('2307', 'Building Diagram', 'To include external and internal layouts and elevations', NULL, NULL, 'CB', 'Architectural', 'AFC, AFU, AFD', 126),
('3309', 'Bill Of Quantities', 'A list of whole assemblies or bulk material showing the quantity of each required.', NULL, NULL, 'CB', 'Architectural', 'IFI, AFU, AFP, AFT', 127),
('3328', 'Installation Manual', 'Installation refers to the mounting, setting, erection, etc. of equipment and accessories.', NULL, NULL, 'CB', 'Architectural', 'IFI, AFU, AFP, AFT', 128),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor as requested in contract procedures', NULL, NULL, 'CB', 'Architectural', 'IFI, AFU, AFP, AFT', 129),
('3366', 'Technical Query', 'Technical Query Includes STQ (Site Technical Query)', NULL, NULL, 'CB', 'Architectural', 'IFI, AFU, AFP, AFT', 130),
('4018', 'General Arrangement Diagram', 'A diagram showing the main features and locations of major items.', 'Tier 1', 'RLMU', 'CB', 'Architectural', 'ASB, AFC, AFU, AFD', 131),
('4018', 'General Arrangement Diagram', 'A diagram showing the main features and locations of major items.', 'Tier 1', 'RLMU', 'CI', 'Infrastructure', 'ASB, AFC, AFU, AFD', 132),
('4018', 'General Arrangement Diagram', 'Shows an assembly of equipment components that may be an exploded view.', 'Tier 1', 'RLMU', 'CS', 'Structures', 'AFC, AFU, AFD', 133),
('5501', 'Accommodation Philosophy', 'Design considerations for accommodating personnel.', NULL, NULL, 'CB', 'Architectural', 'IFI, AFU, AFP, AFT', 134),
('5679', 'Material and Equipment Performance Philosophy', 'Performance requirement for architectural elements.', NULL, NULL, 'CB', 'Architectural', 'IFI, AFU, AFP, AFT', 135),
('5680', 'Other Philosophy', NULL, NULL, NULL, 'CB', 'Architectural', 'IFI, AFU, AFP, AFT', 136),
('7205', 'Technical Deviation Request', 'Request, approval or rejection of changes to a technical specification.', NULL, NULL, 'CB', 'Architectural', 'IFI, AFU, AFP, AFT', 137),
('7303', 'Requisition', 'A request for service or product initiated by the user or consumer.', NULL, NULL, 'CB', 'Architectural', 'IFI, AFU, AFP, AFT', 138),
('7753', 'Terms Of Reference', 'Specifies the scope and details of the activity to which it refers.', NULL, NULL, 'CB', 'Architectural', 'IFI, AFU, AFP, AFT', 139),
('7880', 'Other Specification', 'Specifications for cladding, door, windows, fire & blast wall, ceiling, etc.', NULL, NULL, 'CB', 'Architectural', 'IFI, AFU, AFP, AFT', 140),
('8502', 'Clarification Request', 'Clarification RFI at the start of contract or work order.', NULL, NULL, 'CB', 'Architectural', 'IFI, AFU, AFP, AFT', 141),
('604', 'Piling Plan', 'An arrangement diagram in plan view depicting the location of piles.', NULL, NULL, 'CG', 'Geotechnical/Foundation', 'IFI, AFU, AFP, AFT', 142),
('2331', 'Foundation Design Diagram', 'Details of foundation design for construction.', NULL, NULL, 'CG', 'Geotechnical/Foundation', 'AFC, AFU, AFD', 143),
('2401', 'Pile Make-up Details', 'A diagram that is not a layout plan (see Piling Plan).', NULL, NULL, 'CG', 'Geotechnical/Foundation', 'AFC, AFU, AFD', 144),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'CG', 'Geotechnical/Foundation', 'IFI, AFU, AFP, AFT', 145),
('3366', 'Technical Query', 'Technical Query Includes STQ (Site Technical Query)', NULL, NULL, 'CG', 'Geotechnical/Foundation', 'IFI, AFU, AFP, AFT', 146),
('4017', 'Foundation Layout Diagram', 'An arrangement diagram in plan view depicting the location of foundation/pile supports.', NULL, NULL, 'CG', 'Geotechnical/Foundation', 'AFC, AFU, AFD', 147),
('4018', 'General Arrangement Diagram', 'A diagram showing the main features and locations of major items.', NULL, NULL, 'CG', 'Geotechnical/Foundation', 'AFC, AFU, AFD', 148),
('4024', 'Layout Diagram, Plot Plan', 'Plan view of a area showing exact location of main items of equipment.', NULL, NULL, 'CG', 'Geotechnical/Foundation', 'IFI, AFU, AFP, AFT', 149),
('6968', 'Soil Investigation and Survey Data Report', 'Usually for foundation design or environmental purposes.', NULL, NULL, 'CG', 'Geotechnical/Foundation', 'IFI, AFU, AFP, AFT', 150),
('7303', 'Requisition', 'A request for service or product initiated by the user or consumer.', NULL, NULL, 'CG', 'Geotechnical/Foundation', 'IFI, AFU, AFP, AFT', 151),
('7753', 'Terms Of Reference', 'Specifies the scope and details of the activity to which it refers.', NULL, NULL, 'CG', 'Geotechnical/Foundation', 'IFI, AFU, AFP, AFT', 152),
('7880', 'Other Specification', NULL, NULL, NULL, 'CG', 'Geotechnical/Foundation', 'IFI, AFU, AFP, AFT', 153),
('8502', 'Clarification Request', 'Clarification RFI at the start of contract or work order.', NULL, NULL, 'CG', 'Geotechnical/Foundation', 'IFI, AFU, AFP, AFT', 154),
('1206', 'Design Calculation', 'Prepared in order to prove that the item of equipment or system selected meets the design criteria.', NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 155),
('1380', 'Other Calculation', NULL, NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 156),
('2105', 'Equipment Datasheet', 'Gives precise information about a Tag, Equipment or a Model.', NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 157),
('2305', 'Assembly Diagram', 'Shows an assembly of equipment components that may be an exploded view.', NULL, NULL, 'CS', 'Structures', 'AFC, AFU, AFD', 158),
('2331', 'Foundation Design Diagram', 'Details of foundation design for construction.', NULL, NULL, 'CS', 'Structures', 'AFC, AFU, AFD', 159),
('2358', 'Support Diagram', 'Piping support, pipe rack.', NULL, NULL, 'CS', 'Structures', 'AFC, AFU, AFD', 160),
('2404', 'Construction Diagram', 'Construct is to Erect, Build, or Make (usually) on-site.', NULL, NULL, 'CS', 'Structures', 'AFC, AFU, AFD', 161),
('3309', 'Bill Of Quantities', 'A list of whole assemblies or bulk material showing the quantity of each required.', NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 162),
('3323', 'Technical Note', 'Agreement which describes how an engineering or maintenance issue will be resolved.', NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 163),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 164),
('3366', 'Technical Query', 'Technical Query Includes STQ (Site Technical Query)', NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 165),
('4017', 'Foundation Layout Diagram', 'An arrangement diagram in plan view depicting the location of foundation/pile supports.', NULL, NULL, 'CS', 'Structures', 'AFC, AFU, AFD', 166),
('4024', 'Layout Diagram, Plot Plan', 'Plan view of a area showing exact location of main items of equipment.', NULL, NULL, 'CS', 'Structures', 'AFC, AFU, AFD', 167),
('4306', 'Bill of Materials', 'A list of all parts, sub assemblies and raw materials.', NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 168),
('5507', 'Design Philosophy', 'A set of ideas, beliefs, or underlying theory.', NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 169),
('5680', 'Other Philosophy', NULL, NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 170),
('5880', 'Other Plan', NULL, NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 171),
('6180', 'Other Procedure', NULL, NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 172),
('7180', 'Other Report', NULL, NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 173),
('7205', 'Technical Deviation Request', 'Request, approval or rejection of changes to a technical specification.', NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 174),
('7303', 'Requisition', 'A request for service or product initiated by the user or consumer.', NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 175),
('7739', 'Project Specification', 'A technical description of the information on a Project.', NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 176),
('7753', 'Terms Of Reference', 'Specifies the scope and details of the activity to which it refers.', NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 177),
('7770', 'Other Functional Design Specification', 'Specification that describes the deliverable in terms of form, fit, function, and performance.', NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 178),
('7771', 'Equipment Specification', 'Gives precise information about a Tag, Equipment or a Model.', NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 179),
('7880', 'Other Specification', NULL, NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 180),
('8380', 'Other Study', NULL, NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 181),
('8502', 'Clarification Request', 'Clarification RFI at the start of contract or work order.', NULL, NULL, 'CS', 'Structures', 'IFI, AFU, AFP, AFT', 182),
('602', 'Equipment Location Diagram', 'Shows the physical location of all equipment.', NULL, NULL, 'EA', 'Electrical', 'ASB, AFC, AFU, AFD', 183),
('780', 'Other Assessment Report', 'Health check, GAP analysis etc.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 184),
('901', 'Single Line Diagram', 'A simplified notation for representing an electrical system.', 'Tier 1', 'RLMU', 'EA', 'Electrical', 'ASB, AFC, AFU, AFD', 185),
('980', 'Other Block Diagram', 'A pictorial representation of a process.', NULL, NULL, 'EA', 'Electrical', 'AFC, AFU, AFD', 186),
('1206', 'Design Calculation', 'Prepared in order to prove that the item of equipment or system selected meets the design criteria.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 187),
('1380', 'Other Calculation', NULL, NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 188),
('1580', 'Other Certificate', NULL, NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 189),
('1979', 'Database and Data set', 'Data stored in a proprietary or neutral format.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 190),
('2105', 'Equipment Datasheet', 'Gives precise information about a Tag, Equipment or a Model.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 191),
('2305', 'Assembly Diagram', 'Shows an assembly of equipment components.', NULL, NULL, 'EA', 'Electrical', 'AFC, AFU, AFD', 192),
('2310', 'Cable Block Diagram', 'An overview diagram which represents a cable network system.', 'Tier 2', 'RLMU', 'EA', 'Electrical', 'ASB, AFC, AFU, AFD', 193),
('2325', 'Hazardous Area Classification Diagram', 'Defines the areas within the physical limits of the facility.', 'Tier 1', 'RLMU', 'EA', 'Electrical', 'ASB, AFC, AFU, AFD', 194),
('2335', 'Hook Up Diagram', 'Installation details. May show instrument impulse, pneumatic and electronic connections.', NULL, NULL, 'EA', 'Electrical', 'AFC, AFU, AFD', 195),
('2341', 'Interface Diagram', 'Diagrams showing Interface terminations and hook ups between Contractors', NULL, NULL, 'EA', 'Electrical', 'AFC, AFU, AFD', 196),
('2373', 'Routing Diagram', 'Alignment of cables and pipelines between facilities.', NULL, NULL, 'EA', 'Electrical', 'ASB, AFC, AFU, AFD', 197),
('2389', 'Terminal Connection Diagram', NULL, NULL, NULL, 'EA', 'Electrical', 'AFC, AFU, AFD', 198),
('2503', 'Elementary Diagram', 'A diagram that shows all the elements for one specific function of the circuit.', 'Tier 2', 'RLMU', 'EA', 'Electrical', 'ASB, AFC, AFU, AFD', 199),
('2580', 'Other Schematic Diagram', 'Details the elements and functions of a system with the components represented by symbols.', NULL, NULL, 'EA', 'Electrical', 'AFC, AFU, AFD', 200),
('3309', 'Bill Of Quantities', 'A list of whole assemblies or bulk material showing the quantity of each required.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 201),
('3323', 'Technical Note', 'Agreement which describes how an engineering or maintenance issue will be resolved.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 202),
('3328', 'Installation Manual', 'Installation refers to the mounting, setting, erection, etc. of equipment.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 203),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 204),
('3366', 'Technical Query', 'Technical Query Includes STQ (Site Technical Query)', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 205),
('3375', 'Work Instruction', 'Self Explanatory', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 206),
('4005', 'Cable Tray Layout Diagram', NULL, NULL, NULL, 'EA', 'Electrical', 'AFC, AFU, AFD', 207),
('4013', 'Field Auxiliary Room Layout Diagram', 'Substation, MCC room etc.', 'Tier 2', 'RLMU', 'EA', 'Electrical', 'AFC, AFU, AFD', 208),
('4024', 'Layout Diagram, Plot Plan', 'Plan view of a area showing exact location of main items of equipment.', NULL, NULL, 'EA', 'Electrical', 'ASB, AFC, AFU, AFD', 209),
('4180', 'Other Layout Diagram', NULL, NULL, NULL, 'EA', 'Electrical', 'AFC, AFU, AFD', 210),
('4306', 'Bill of Materials', 'A list of all parts, sub assemblies and raw materials.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 211),
('4308', 'Cable List', 'List of all cables, their specifications and end points.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 212),
('4380', 'Other List', NULL, NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 213),
('4816', 'Method Statement', NULL, NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 214),
('5280', 'Other Multimedia', NULL, NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 215),
('5507', 'Design Philosophy', 'A set of ideas, beliefs, or underlying theory.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 216),
('5509', 'Electrical Design Philosophy', 'Philosophy of Electrical Power Generation and Distribution.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 217),
('5514', 'Grounding and Lightning Protection Philosophy', NULL, NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 218),
('5680', 'Other Philosophy', NULL, NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 219),
('5880', 'Other Plan', NULL, NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 220),
('6067', 'Acceptance Test Procedure', 'Includes FAT and non-FAT procedures.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 221),
('6180', 'Other Procedure', NULL, NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 222),
('6612', 'Equipment Register', 'Master Tag and Equipment list.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 223),
('7180', 'Other Report', NULL, NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 224),
('7205', 'Technical Deviation Request', 'Request, approval or rejection of changes to a technical specification.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 225),
('7303', 'Requisition', 'A request for service or product initiated by the user or consumer.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 226),
('7739', 'Project Specification', 'A technical description of the information on a Project.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 227),
('7753', 'Terms Of Reference', 'Specifies the scope and details of the activity to which it refers.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 228),
('7770', 'Other Functional Design Specification', 'Specification that describes the deliverable in terms of form, fit, function, and performance.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 229),
('7771', 'Equipment Specification', 'Gives precise information about a Tag, Equipment or a Model.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 230),
('7880', 'Other Specification', NULL, NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 231),
('8380', 'Other Study', NULL, NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 232),
('8502', 'Clarification Request', 'Clarification RFI at the start of contract or work order.', NULL, NULL, 'EA', 'Electrical', 'IFI, AFU, AFP, AFT', 233),
('8804', 'Connection Diagram', 'Details of cable numbers and terminations between vendor packages.', NULL, NULL, 'EA', 'Electrical', 'AFC, AFU, AFD', 234),
('8880', 'Other Wiring Diagram', NULL, NULL, NULL, 'EA', 'Electrical', 'AFC, AFU, AFD', 235),
('780', 'Other Assessment Report', 'Health check, GAP analysis etc.', NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 236),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 237),
('3366', 'Technical Query', 'Technical Query Includes STQ (Site Technical Query)', NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 238),
('5508', 'Drainage Philosophy', NULL, NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 239),
('5512', 'Environmental Philosophy', NULL, NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 240),
('5680', 'Other Philosophy', NULL, NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 241),
('5713', 'Environmental Management Plan', NULL, NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 242),
('5880', 'Other Plan', NULL, NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 243),
('6180', 'Other Procedure', NULL, NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 244),
('6612', 'Equipment Register', 'Master Tag and Equipment list.', NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 245),
('6840', 'Discharge Assessment Report', NULL, NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 246),
('6852', 'Environmental Impact Assessment Report', 'Report outlining environmental impact assessment of the project.', NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 247),
('7180', 'Other Report', NULL, NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 248),
('7205', 'Technical Deviation Request', 'Request, approval or rejection of changes to a technical specification.', NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 249),
('7303', 'Requisition', 'A request for service or product initiated by the user or consumer.', NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 250),
('7739', 'Project Specification', 'A technical description of the information on a Project.', NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 251),
('7753', 'Terms Of Reference', 'Specifies the scope and details of the activity to which it refers.', NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 252),
('7880', 'Other Specification', NULL, NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 253),
('8380', 'Other Study', NULL, NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 254),
('8502', 'Clarification Request', 'Clarification RFI at the start of contract or work order.', NULL, NULL, 'HA', 'Environmental', 'IFI, AFU, AFP, AFT', 255),
('602', 'Equipment Location Diagram', 'Shows the physical location of all equipment.', NULL, NULL, 'HX', 'HSE&S General', 'ASB, AFC, AFU, AFD', 256),
('780', 'Other Assessment Report', 'Health check, GAP analysis etc.', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 257),
('1206', 'Design Calculation', 'Prepared in order to prove that the item of equipment or system selected meets the design criteria.', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 258),
('2325', 'Hazardous Area Classification Diagram', 'Defines the areas within the physical limits of the facility.', 'Tier 1', 'RLMU', 'HX', 'HSE&S General', 'ASB, AFC, AFU, AFD', 259),
('3309', 'Bill Of Quantities', 'A list of whole assemblies or bulk material.', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 260),
('3323', 'Technical Note', 'Agreement which describes how an engineering or maintenance issue will be resolved.', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 261),
('3328', 'Installation Manual', 'Installation refers to the mounting, setting, erection, etc. of equipment.', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 262),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 263),
('3366', 'Technical Query', 'Technical Query Includes STQ (Site Technical Query)', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 264),
('4024', 'Layout Diagram, Plot Plan', 'Plan view of a area showing exact location of main items of equipment.', NULL, NULL, 'HX', 'HSE&S General', 'ASB, AFC, AFU, AFD', 265),
('4306', 'Bill of Materials', 'A list of all parts, sub assemblies and raw materials.', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 266),
('4816', 'Method Statement', NULL, NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 267),
('5160', 'Forms & Templates', NULL, NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 268),
('5280', 'Other Multimedia', NULL, NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 269),
('5510', 'Escape Route Philosophy', NULL, NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 270),
('5513', 'Fire and Gas Philosophy', NULL, NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 271),
('5680', 'Other Philosophy', NULL, NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 272),
('5716', 'HSE Plan', 'HSE Management Plans.', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 273),
('5880', 'Other Plan', NULL, NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 274),
('6180', 'Other Procedure', NULL, NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 275),
('6680', 'Other Register', NULL, NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 276),
('6802', 'Active Fire Protection System Data Report', 'Design data for active fire fighting systems.', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 277),
('6820', 'Closeout Report', 'Provides an overview what has been done, what has been delivered.', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 278),
('6854', 'Ergonomic Report', NULL, NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 279),
('6873', 'Hazard Identification Report', 'Hazards Identification report following the Project Safety Review (HAZID).', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 280),
('6874', 'Hazard Management Physical Effects Modelling Report', NULL, NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 281),
('7180', 'Other Report', NULL, NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 282),
('7205', 'Technical Deviation Request', 'Request, approval or rejection of changes to a technical specification.', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 283),
('7303', 'Requisition', 'A request for service or product initiated by the user or consumer.', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 284),
('7506', 'Design HSE Case', 'Demonstrates ALARP - Design & Operate Cases', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 285),
('7739', 'Project Specification', 'A technical description of the information on a Project.', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 286),
('7753', 'Terms Of Reference', 'Specifies the scope and details of the activity to which it refers.', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 287),
('7876', 'Performance Standard For Safety Critical Element', 'A statement of the performance required of a system or item of equipment.', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 288),
('7880', 'Other Specification', NULL, NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 289),
('8218', 'Design Layout Study', 'A work that results from studious endeavour.', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 290),
('8380', 'Other Study', NULL, NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 291),
('8502', 'Clarification Request', 'Clarification RFI at the start of contract or work order.', NULL, NULL, 'HX', 'HSE&S General', 'IFI, AFU, AFP, AFT', 292),
('602', 'Equipment Location Diagram', 'Shows the physical location of all equipment.', NULL, NULL, 'IN', 'Instrumentation', 'ASB, AFC, AFU, AFD', 293),
('780', 'Other Assessment Report', 'Health check, GAP analysis etc.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 294),
('0901', 'Control System Block Diagram', 'Pictorial representation of the processes performed by a control system.', 'Tier 2', 'RLMU', 'IN', 'Instrumentation', 'AFC, AFU, AFD', 295),
('2305', 'Assembly Diagram', 'Shows an assembly of equipment components.', NULL, NULL, 'IN', 'Instrumentation', 'AFC, AFU, AFD', 296),
('2312', 'Control System Diagram', 'Gives a pictorial representation of the main elements and functions of a control circuit/system.', 'Tier 2', 'RLMU', 'IN', 'Instrumentation', 'AFC, AFU, AFD', 297),
('2347', 'Loop Diagram', 'Details all elements of a control loop, from sensing element through to controlling element.', 'Tier 2', 'RLMU', 'IN', 'Instrumentation', 'ASB, AFC, AFU, AFD', 298),
('4013', 'Field Auxiliary Room Layout Diagram', 'UPS battery room only', 'Tier 2', 'RLMU', 'IN', 'Instrumentation', 'AFC, AFU, AFD', 299),
('2105', 'Equipment Datasheet', 'Gives precise information about a Tag, Equipment or a Model.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 300),
('980', 'Other Block Diagram', 'A pictorial representation of a process.', NULL, NULL, 'IN', 'Instrumentation', 'AFC, AFU, AFD', 301),
('1380', 'Other Calculation', NULL, NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 302),
('1580', 'Other Certificate', NULL, NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 303),
('1979', 'Database and Data set', 'Data stored in a proprietary or neutral format.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 304),
('2320', 'Equipment Cross Section Diagram', NULL, NULL, NULL, 'IN', 'Instrumentation', 'AFC, AFU, AFD', 305),
('2335', 'Hook Up Diagram', 'Installation details. May show the instrument impulse, pneumatic and electronic connections.', NULL, NULL, 'IN', 'Instrumentation', 'AFC, AFU, AFD', 306),
('2341', 'Interface Diagram', 'Diagrams showing Interface terminations and hook ups between Contractors', NULL, NULL, 'IN', 'Instrumentation', 'AFC, AFU, AFD', 307),
('2373', 'Routing Diagram', 'Alignment of cables and pipelines between facilities.', NULL, NULL, 'IN', 'Instrumentation', 'ASB, AFC, AFU, AFD', 308),
('2389', 'Terminal Connection Diagram', NULL, NULL, NULL, 'IN', 'Instrumentation', 'AFC, AFU, AFD', 309),
('3309', 'Bill Of Quantities', 'A list of whole assemblies or bulk material.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 310),
('3323', 'Technical Note', 'Agreement which describes how an engineering or maintenance issue will be resolved.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 311),
('3328', 'Installation Manual', 'Installation refers to the mounting, setting, erection, etc.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 312),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 313),
('3366', 'Technical Query', 'Technical Query Includes STQ (Site Technical Query)', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 314),
('3375', 'Work Instruction', 'Self Explanatory', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 315),
('4005', 'Cable Tray Layout Diagram', NULL, NULL, NULL, 'IN', 'Instrumentation', 'AFC, AFU, AFD', 316),
('4024', 'Layout Diagram, Plot Plan', 'Plan view of a area showing exact location of main items.', NULL, NULL, 'IN', 'Instrumentation', 'ASB, AFC, AFU, AFD', 317),
('4180', 'Other Layout Diagram', NULL, NULL, NULL, 'IN', 'Instrumentation', 'AFC, AFU, AFD', 318),
('4306', 'Bill of Materials', 'A list of all parts, sub assemblies and raw materials.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 319),
('4308', 'Cable List', 'List of all cables, their specifications and end points.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 320),
('8804', 'Connection Diagram', 'Details of cable numbers and terminations between vendor packages.', NULL, NULL, 'IN', 'Instrumentation', 'AFC, AFU, AFD', 321),
('8880', 'Other Wiring Diagram', NULL, NULL, NULL, 'IN', 'Instrumentation', 'AFC, AFU, AFD', 322),
('4327', 'Input, Output List', 'List to show input and output of an equipment connected to other equipments.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 323),
('5306', 'Process Control Narrative', 'Description of the process control functionality.', 'Tier 2', 'RLMU', 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 324),
('5505', 'Control Philosophy', 'Describes start-up and shutdown requirements of the process.', 'Tier 2', 'RLMU', 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 325),
('4382', 'I/O list-Process, ESD, F&G', NULL, NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 326),
('4780', 'Other Logic diagram', 'A graphical representation of a system using formal logic.', 'Tier 2', 'RLMU', 'IN', 'Instrumentation', 'ASB, AFC, AFU, AFD', 327),
('5531', 'Safeguarding Philosophy', NULL, NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 328),
('7709', 'Control System Functional Specification', 'Functional Description of Integrated Control and Safeguarding System', 'Tier 2', 'RLMU', 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 329),
('7710', 'Control, Safeguarding Specification', NULL, 'Tier 2', 'RLMU', 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 330),
('4380', 'Other List', NULL, NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 331),
('4816', 'Method Statement', NULL, NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 332),
('5280', 'Other Multimedia', NULL, NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 333),
('5507', 'Design Philosophy', 'A set of ideas, beliefs, or underlying theory.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 334),
('5520', 'Metering Philosophy', NULL, NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 335),
('5680', 'Other Philosophy', NULL, NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 336),
('5880', 'Other Plan', NULL, NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 337),
('6067', 'Acceptance Test Procedure', 'Includes FAT and non-FAT procedures.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 338),
('6180', 'Other Procedure', NULL, NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 339),
('6612', 'Equipment Register', 'Master Tag and Equipment list.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 340),
('7180', 'Other Report', NULL, NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 341),
('7205', 'Technical Deviation Request', 'Request, approval or rejection of changes to a technical specification.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 342),
('7303', 'Requisition', 'A request for service or product.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 343),
('7731', 'Network Architecture Specification', NULL, NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 344),
('7739', 'Project Specification', 'A technical description of the information on a Project.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 345),
('7753', 'Terms Of Reference', 'Specifies the scope and details of the activity to which it refers.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 346),
('7770', 'Other Functional Design Specification', 'Specification that describes the deliverable.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 347),
('7771', 'Equipment Specification', 'Gives precise information about a Tag, Equipment or a Model.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 348),
('7880', 'Other Specification', NULL, NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 349),
('8380', 'Other Study', NULL, NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 350),
('8502', 'Clarification Request', 'Clarification RFI at the start of contract or work order.', NULL, NULL, 'IN', 'Instrumentation', 'IFI, AFU, AFP, AFT', 351),
('510', 'Stability Analysis Report', NULL, NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 352),
('515', 'Upheaval Buckling Analysis Report', NULL, NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 353),
('580', 'Other Analysis Report', NULL, NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 354),
('1206', 'Design Calculation', 'Prepared in order to prove that the item meets the design criteria.', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 355),
('1231', 'Weight Calculation', 'Includes Mass, Buoyancy, and calculations used in the design of weight coating.', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 356),
('1380', 'Other Calculation', NULL, NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 357),
('2105', 'Equipment Datasheet', 'Gives precise information about a Tag, Equipment or a Model.', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 358),
('2373', 'Routing Diagram', 'Alignment of cables and pipelines between facilities.', 'Tier 2', 'RLMU', 'LA', 'Pipelines', 'ASB, AFC, AFU, AFD', 359),
('3323', 'Technical Note', 'Agreement which describes how an issue will be resolved.', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 360),
('3328', 'Installation Manual', 'Installation refers to the mounting, setting, erection.', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 361),
('3331', 'Design Summary', 'A document explaining how the design of a major part of a facility has been conducted.', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 362),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 363),
('3366', 'Technical Query', 'Technical Query Includes STQ', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 364),
('3880', 'Other Inspection Report', NULL, NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 365),
('4024', 'Layout Diagram, Plot Plan', 'Plan view of a area showing exact location.', NULL, NULL, 'LA', 'Pipelines', 'AFC, AFU, AFD', 366),
('4033', 'Piping Layout Diagram', 'Shows the precise location of piping and ducting within a facility.', NULL, NULL, 'LA', 'Pipelines', 'ASB, AFC, AFU, AFD', 367),
('4306', 'Bill of Materials', 'A list of all parts, sub assemblies and raw materials.', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 368),
('4816', 'Method Statement', NULL, NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 369),
('5280', 'Other Multimedia', NULL, NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 370),
('5507', 'Design Philosophy', 'A set of ideas, beliefs, or underlying theory.', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 371),
('5680', 'Other Philosophy', NULL, NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 372),
('5880', 'Other Plan', NULL, NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 373),
('6180', 'Other Procedure', NULL, NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 374),
('6612', 'Equipment Register', 'Master Tag and Equipment list.', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 375),
('7180', 'Other Report', NULL, NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 376),
('7205', 'Technical Deviation Request', 'Request, approval or rejection of changes.', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 377),
('7303', 'Requisition', 'A request for service or product.', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 378),
('7739', 'Project Specification', 'A technical description of the information on a Project.', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 379),
('7753', 'Terms Of Reference', 'Specifies the scope and details of the activity.', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 380),
('7770', 'Other Functional Design Specification', 'Specification that describes the deliverable.', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 381),
('7771', 'Equipment Specification', 'Gives precise information about a Tag, Equipment or a Model.', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 382),
('7880', 'Other Specification', NULL, NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 383),
('8380', 'Other Study', NULL, NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 384),
('8502', 'Clarification Request', 'Clarification RFI at the start of contract.', NULL, NULL, 'LA', 'Pipelines', 'IFI, AFU, AFP, AFT', 385),
('780', 'Other Assessment Report', 'Health check, GAP analysis etc.', NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 386),
('1206', 'Design Calculation', 'Prepared in order to prove that the item meets the design criteria.', NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 387),
('1380', 'Other Calculation', NULL, NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 388),
('2105', 'Equipment Datasheet', 'Gives precise information about a Tag, Equipment or a Model.', NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 389),
('2305', 'Assembly Diagram', 'Shows an assembly of equipment components.', NULL, NULL, 'MA', 'Mechanical Rotating', 'AFC, AFU, AFD', 390),
('3323', 'Technical Note', 'Agreement which describes how an issue will be resolved.', NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 391),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 392),
('3366', 'Technical Query', 'Technical Query Includes STQ', NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 393),
('4816', 'Method Statement', NULL, NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 394),
('5280', 'Other Multimedia', NULL, NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 395),
('5680', 'Other Philosophy', NULL, NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 396),
('6067', 'Acceptance Test Procedure', 'Includes FAT and non-FAT procedures.', NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 397),
('6180', 'Other Procedure', NULL, NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 398),
('6612', 'Equipment Register', 'Master Tag and Equipment list.', NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 399),
('7180', 'Other Report', NULL, NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 400),
('7205', 'Technical Deviation Request', 'Request, approval or rejection of changes.', NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 401),
('7303', 'Requisition', 'A request for service or product.', NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 402),
('7739', 'Project Specification', 'A technical description of the information on a Project.', NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 403),
('7753', 'Terms Of Reference', 'Specifies the scope and details of the activity.', NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 404),
('7771', 'Equipment Specification', 'Gives precise information about a Tag, Equipment or a Model.', NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 405),
('7880', 'Other Specification', NULL, NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 406),
('8380', 'Other Study', NULL, NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 407),
('8502', 'Clarification Request', 'Clarification RFI at the start of contract.', NULL, NULL, 'MA', 'Mechanical Rotating', 'IFI, AFU, AFP, AFT', 408);
