INSERT INTO dms_document_type_acronyms (acronym, full_name, type_code, notes, is_learned)
VALUES
  ('MDS', 'Material Data Sheet', '', 'Material specification', false),
  ('MRB', 'Material Requisition for Bulk', '', 'Bulk procurement', false),
  ('TBE', 'Technical Bid Evaluation', '', 'Vendor evaluation', false),
  ('TBA', 'Technical Bid Analysis', '', 'Vendor analysis', false),
  ('VDR', 'Vendor Document Register', '', 'Vendor document tracking', false),
  ('ESDV', 'Emergency Shutdown Valve', '', 'Safety system component', false),
  ('PFD', 'Process Flow Diagram', '', 'Process flow', false),
  ('FEED', 'Front End Engineering Design', '', 'Engineering phase', false),
  ('EPC', 'Engineering Procurement Construction', '', 'Project phase', false),
  ('SLD', 'Single Line Diagram', '', 'Electrical diagram', false),
  ('GA', 'General Arrangement', '', 'Layout drawing', false),
  ('GAD', 'General Arrangement Drawing', '', 'Layout drawing', false),
  ('CDB', 'Control and Distribution Board', '', 'Electrical equipment', false),
  ('HYD', 'Hydraulic', '', 'Hydraulic system', false),
  ('PTR', 'Pressure Test Report', '', 'Testing documentation', false),
  ('PCOM', 'Pre-Commissioning', '', 'Commissioning phase', false),
  ('COM', 'Commissioning', '', 'Commissioning phase', false),
  ('HAR', 'Hazard Assessment Report', '', 'Safety study', false),
  ('RAR', 'Risk Assessment Report', '', 'Risk evaluation', false),
  ('HAC', 'Hazardous Area Classification', '', 'Safety classification', false),
  ('PCN', 'Project Change Notice', '', 'Change management', false),
  ('PES', 'Process Engineering Specification', '', 'Process specification', false),
  ('HEMP', 'Hazard and Effects Management Process', '', 'Safety management', false),
  ('SIS', 'Safety Instrumented System', '', 'Safety system', false),
  ('SIL', 'Safety Integrity Level', '', 'Safety assessment', false),
  ('FAT', 'Factory Acceptance Test', '', 'Testing phase', false),
  ('SAT', 'Site Acceptance Test', '', 'Testing phase', false),
  ('MTO', 'Material Take-Off', '', 'Quantity survey', false),
  ('BOQ', 'Bill of Quantities', '', 'Quantity listing', false),
  ('HAZID', 'Hazard Identification', '', 'Safety study', false),
  ('HAZOP', 'Hazard and Operability Study', '', 'Safety study', false),
  ('SIR', 'Safety Integrity Review', '', 'Safety review', false),
  ('PSV', 'Pressure Safety Valve', '', 'Safety device', false),
  ('PRV', 'Pressure Relief Valve', '', 'Safety device', false),
  ('TQ', 'Technical Query', '', 'Project communication', false),
  ('RFI', 'Request for Information', '', 'Project communication', false),
  ('RFQ', 'Request for Quotation', '', 'Procurement', false),
  ('AFC', 'Approved for Construction', '', 'Document status', false),
  ('AFU', 'Approved for Use', '', 'Document status', false),
  ('IFC', 'Issued for Construction', '', 'Document status', false),
  ('IFR', 'Issued for Review', '', 'Document status', false),
  ('IFA', 'Issued for Approval', '', 'Document status', false),
  ('DCS', 'Distributed Control System', '', 'Control system', false),
  ('PLC', 'Programmable Logic Controller', '', 'Control system', false),
  ('SCADA', 'Supervisory Control and Data Acquisition', '', 'Control system', false),
  ('UFD', 'Utility Flow Diagram', '', 'Utility process diagram', false),
  ('MR', 'Material Requisition', '', 'Procurement document', false),
  ('ITB', 'Invitation to Bid', '', 'Procurement phase', false),
  ('LLI', 'Long Lead Item', '', 'Procurement category', false),
  ('ROS', 'Required on Site', '', 'Scheduling milestone', false)
ON CONFLICT DO NOTHING;