
-- Soft-delete all existing PSSR checklist items
UPDATE public.pssr_checklist_items SET is_active = false WHERE is_active = true;

-- Insert Design Integrity items (category: 2812e48a-9516-40e5-af05-e74e64bca55c)
INSERT INTO public.pssr_checklist_items (category, topic, description, supporting_evidence, guidance_notes, responsible, approvers, sequence_number, is_active, version) VALUES
('2812e48a-9516-40e5-af05-e74e64bca55c', 'DEM 1', 'Does the design and construction of the new or modified asset comply with the approved engineering standards and requirements?', 'DEM 1 Compliance Report', E'• Confirm the design and construction comply with the approved engineering standards, including DEM‑1.\n• Ensure all deviations or waivers from design standards are formally approved, documented, and captured as Qualifications.', 'BFM Lead', 'Process TA2, PACO TA2, Elect TA2, Static TA2, Rotating TA2, Tech Safety TA2, MCI TA2, Civil TA2', 1, true, 1),
('2812e48a-9516-40e5-af05-e74e64bca55c', 'DEM 2', 'Does the design and construction of the new or modified asset comply with the Process Safety Basic Requirements (DEM‑2)?', 'DEM 2 Compliance Report', E'• Verify that the design and construction comply with all applicable Process Safety Basic Requirements (PSBRs) as defined in DEM‑2.\n• Review and document any deviations or derogations from DEM‑2 requirements, ensuring they are formally approved, risk‑assessed, and captured as Qualifications where applicable.', 'BFM Lead', 'Process TA2, PACO TA2, Elect TA2, Static TA2, Rotating TA2, Tech Safety TA2, MCI TA2, Civil TA2', 2, true, 1),
('2812e48a-9516-40e5-af05-e74e64bca55c', 'HSSE Case', 'Has Operational ALARP been demonstrated, including SIMOPS and MOPO requirements, and documented in the Operational HSSE Case?', E'Operations HSSE Case\nALARP Demonstration Report', E'• The Operations HSSE Case has been fully completed, formally approved, and cascaded to all relevant personnel.\n• There is clear demonstration and assurance that all HSSE risks are tolerable and have been reduced to ALARP.\n• All Safety‑Critical Elements (SCEs) have been identified, documented, and incorporated into the Operations HSSE Case.', 'BFM Lead', 'Process TA2, PACO TA2, Elect TA2, Static TA2, Rotating TA2, Tech Safety TA2, MCI TA2, Civil TA2', 3, true, 1);

-- Insert Technical Integrity items (category: 6d7477e9-cdba-4a9f-860b-e64d15e7e655)
INSERT INTO public.pssr_checklist_items (category, topic, description, supporting_evidence, guidance_notes, responsible, approvers, sequence_number, is_active, version) VALUES
('6d7477e9-cdba-4a9f-860b-e64d15e7e655', 'Scope', 'Have all agreed scopes been completed, verified, and accepted, with no outstanding works that could impact system readiness, safety, or handover to Operations?', E'Completions Dossiers\nCompletions Reports', E'• All Construction, Commissioning and Maintenance activities must be completed and verified, including Mechanical Completion, functional testing, and closure of A and B punch items.\n• Documentation must be fully updated and accepted, such as ITRs, test packs, redlines/as‑builts, and commissioning records.\n• Any remaining works must be reviewed and confirmed as non‑impacting to safety, operability, or system readiness, with outstanding items formally captured as Qualifications where applicable.', NULL, 'Process TA2, PACO TA2, Elect TA2, Static TA2, Rotating TA2, Tech Safety TA2, MCI TA2, Civil TA2, BFM Lead, Mtce Mgr. Static, Mtce Mgr. Rotating, Mtce Mgr. Instrument, Mtce Mgr. Elect, Site Engr., Ops Team Lead', 1, true, 1),
('6d7477e9-cdba-4a9f-860b-e64d15e7e655', 'MoCs', 'Have all MOC actions been completed and verified on site, and have any remaining actions been checked to ensure they pose no safety or operational risk?', 'Project MOC Report', E'• All MOC actions have been implemented, verified on site, and fully reflected in updated documentation (e.g., P&IDs, C&E, operating procedures, HSSE Case).\n• Technical Authority approval has been obtained for all completed changes.\n• Any remaining MOC actions have been reviewed and risk‑assessed, confirming no safety, integrity, regulatory, or operational impact.', 'BFM Project Engr', 'Process TA2, PACO TA2, Elect TA2, Static TA2, Rotating TA2, Tech Safety TA2, MCI TA2, Civil TA2, BFM Lead', 2, true, 1),
('6d7477e9-cdba-4a9f-860b-e64d15e7e655', 'Safeguarding Systems', 'Have all Safeguarding and Emergency Shutdown systems been successfully tested and confirmed to be in service?', 'Cause & Effect Sheet', E'• All safeguarding and ESD functions must be tested and verified against the approved Cause & Effects (C&E) matrix, confirming that each input triggers the correct shutdown, trip, alarm, or isolation response.\n• Test results must be evidenced and signed off by Commissioning, Operations, and the appropriate Technical Authorities, with all failures corrected and re‑tested.\n• C&E diagrams, SIF registers, and related documentation must be updated, and any outstanding items must be risk‑assessed and raised as Qualifications if they could impact safety or operability.', 'Mtce Mgr. Instrument', 'PACO TA2, Mtce Mgr. Instrument, Site Engr., Ops Team Lead', 3, true, 1),
('6d7477e9-cdba-4a9f-860b-e64d15e7e655', 'FGS', 'Are all Fire and Gas (F&G) systems fully tested and confirmed to be in service?', 'FGS Cause & Effect Sheet', E'• Verify that all F&G detectors, panels, alarms, and trip functions have been function‑tested and confirmed to operate per the approved Cause & Effects (C&E) matrices.\n• Confirm that any inhibited, bypassed, or overridden F&G points have been removed from bypass and returned to service.\n• Ensure field verification has been completed, including physical checks of detector placement, tagging, calibration validity, and communication with the control system.', 'Mtce Mgr. Instrument', 'PACO TA2, Mtce Mgr. Instrument, Site Engr., Ops Team Lead', 4, true, 1),
('6d7477e9-cdba-4a9f-860b-e64d15e7e655', 'Flange Management', 'Has a tightness review been completed, confirming all required flange torquing, and have any additional tightness checks been performed where needed?', 'Flange Management Report', E'• Verify that all flanges associated with isolations, reinstatement, and system preparation have been correctly torqued and documented.\n• Confirm that the tightness review includes any required re‑checks following changes in temperature, pressure, or operating conditions.\n• Ensure field verification has been completed, including physical inspection of flanges, spades/blinds, and isolation points.', 'Mtce Mgr. Static', 'Static TA2, Mtce Mgr. Static, Site Engr., Ops Team Lead', 5, true, 1),
('6d7477e9-cdba-4a9f-860b-e64d15e7e655', 'Relief Valves', 'Are all Relief Valves in service, correctly lined‑up, tagged, and within valid certification?', 'PSV Certificates', E'• Verify that all Relief Valves (PSVs/PRVs) are in service and correctly lined‑up, ensuring isolation valves are in the proper operating position.\n• Confirm each Relief Valve is tagged and traceable, with tags legible and matched to the latest P&IDs, equipment lists, and isolation documentation.\n• Ensure all Relief Valves have current certification and are within their inspection and test validity period.', 'Mtce Mgr. Static', 'Static TA2, Mtce Mgr. Static, Site Engr., Ops Team Lead', 6, true, 1),
('6d7477e9-cdba-4a9f-860b-e64d15e7e655', 'Leak Test', 'Have all applicable equipment been leak‑tested and confirmed oxygen‑free?', 'Leak Test Report', E'• Verify all equipment requiring leak‑testing has been tested.\n• Confirm oxygen‑free status using an Authorized Gas Tester (AGT), ensuring readings are taken for O₂ at all required levels and locations.\n• Ensure all test results have been documented, communicated, and re‑checked after breaks or operational changes.', 'Mtce Mgr. Static', 'Static TA2, Mtce Mgr. Static, Site Engr., Ops Team Lead', 7, true, 1),
('6d7477e9-cdba-4a9f-860b-e64d15e7e655', 'Cleanliness & Dryness', 'Is the equipment clean, dry, and confirmed to meet the required dew point?', 'Cleanliness & Dryness Report', E'• Confirm that the piping/pipeline has been fully drained, flushed, purged, and vented as required.\n• Ensure drying is complete and the measured dew point meets the required project/start‑up specification, with test results recorded and any deviations resolved.', 'Commissioning Lead', 'Static TA2, Mtce Mgr. Static, Site Engr., Ops Team Lead, Pipeline Engr.', 8, true, 1),
('6d7477e9-cdba-4a9f-860b-e64d15e7e655', 'Cathodic Protection', 'Is the Cathodic Protection (CP) System in service and functioning correctly?', 'DCVG and CIPS Reports', E'• Verify that the CP system is energized, operational, and providing adequate protection to pipelines, buried vessels, and metallic structures.\n• Confirm that all CP readings, rectifier outputs, potentials, and alarms are within acceptable limits.\n• Ensure inspection and maintenance records are current, including recent surveys, continuity checks, and grounding verification.', 'Commissioning Lead', 'Elect TA2, Static TA2, Mtce Mgr. Elect, Site Engr., Ops Team Lead, Pipeline Engr.', 9, true, 1),
('6d7477e9-cdba-4a9f-860b-e64d15e7e655', 'Ex Register', 'Have all Ex (Hazardous Area) Equipment been inspected and confirmed to be within valid certification?', 'Ex Register', E'• Verify that all Ex‑rated electrical and instrumentation equipment in hazardous areas has undergone the required inspections.\n• Confirm that each item of Ex equipment is within its valid inspection/certification period.\n• Ensure Ex equipment condition is verified in the field, including correct tagging, earthing/bonding integrity, enclosure condition.', 'Commissioning Lead', 'Static TA2, Mtce Mgr. Elect, Site Engr., Ops Team Lead', 10, true, 1);

-- Insert Operating Integrity items (category: 1219119f-fd54-4306-a0cf-ed1ee3513955)
INSERT INTO public.pssr_checklist_items (category, topic, description, supporting_evidence, guidance_notes, responsible, approvers, sequence_number, is_active, version) VALUES
('1219119f-fd54-4306-a0cf-ed1ee3513955', 'PSSR Walkdown', 'Has a PSSR walkdown been carried out and all Priority 1 actions closed out?', 'Action Close-Out Report', E'• Verify that all findings and actions from PSSR walkdowns reviews are completed, with evidence of closure and sign‑off by responsible Technical Authorities or discipline leads.\n• Ensure any open items have been risk‑assessed and confirmed not to impact safety, operability, regulatory compliance, or start‑up readiness.\n• Confirm that closure evidence is documented and stored in the approved repository.', 'Ops Team Lead', 'Process TA2, PACO TA2, Elect TA2, Static TA2, Rotating TA2, Tech Safety TA2, MCI TA2, Civil TA2, BFM Lead, Pipeline Engr., Mtce Mgr. Static, Mtce Mgr. Rotating, Mtce Mgr. Instrument, Mtce Mgr. Elect, Site Engr., Ops Team Lead, Ops HSE Adviser', 1, true, 1),
('1219119f-fd54-4306-a0cf-ed1ee3513955', 'Documentation', 'Have Red‑Line Mark‑Ups (RLMU/RLMP) for all Tier 1 and 2 Critical Documents available to the Asset?', 'Tier 1 & 2 Documents', E'• All Tier 1 & Tier 2 Critical Documents and Drawings must be red‑lined to as‑built status, formally reviewed, and approved.\n• Controlled copies at site and office must be current and accurate.\n• All Operations and Maintenance documentation must be complete and reflect the final installed condition.\n• Ops Team must have easy access to the latest approved documentation.', 'Ops Team Lead', 'BFM Lead, Pipeline Engr., Mtce Mgr. Static, Mtce Mgr. Rotating, Mtce Mgr. Instrument, Mtce Mgr. Elect, Site Engr., Ops Team Lead', 2, true, 1),
('1219119f-fd54-4306-a0cf-ed1ee3513955', 'PTW', 'Have all open permits been fully suspended or closed?', NULL, E'• Verify that all construction and commissioning permits have been suspended or closed in the PTW system.\n• Confirm that associated isolations have been closed or transferred to Extended Period Isolations (EPIs).\n• Ensure the Project team has handed over all PTW documentation, records, and status to the Asset.', 'Ops Team Lead', 'BFM Lead, Mtce Mgr. Static, Mtce Mgr. Rotating, Mtce Mgr. Instrument, Mtce Mgr. Elect, Site Engr., Ops Team Lead, Ops HSE Adviser', 3, true, 1),
('1219119f-fd54-4306-a0cf-ed1ee3513955', 'Overrides', 'Have all overrides been reviewed and documented in the Override Register?', 'Override Register', E'• Verify that all active, temporary, and historical overrides are recorded in the Override Register.\n• Confirm that each override has been formally reviewed by Operations and the relevant Technical Authorities.\n• Ensure that overrides have been communicated through shift handovers, PTW/SIMOPS processes, and control room logs.', 'Ops Team Lead', 'PACO TA2, Elect TA2, Mtce Mgr. Instrument, Mtce Mgr. Elect, Site Engr., Ops Team Lead', 4, true, 1),
('1219119f-fd54-4306-a0cf-ed1ee3513955', 'Resourcing', 'Has the required Operations & Maintenance Organization been identified and resourced?', 'Organization Chart (with names)', E'• Competency Management Framework & Plan for Operations and Maintenance staff is in place.\n• Technical & HSE critical positions competence criteria has been defined and agreed.\n• HSE Critical Positions have been identified and staff nominated.\n• Personnel in HSSE Critical Roles are "fit for work".', 'Ops Team Lead', 'Pipeline Engr., Mtce Mgr. Static, Mtce Mgr. Rotating, Mtce Mgr. Instrument, Mtce Mgr. Elect, Site Engr., Ops Team Lead, Ops HSE Adviser', 5, true, 1),
('1219119f-fd54-4306-a0cf-ed1ee3513955', 'Training', 'Have all identified and agreed training requirements been completed?', 'Training Records', E'• Verify that all required competency‑based, mandatory, and role‑specific training has been completed.\n• Confirm that project‑specific and facility‑specific training has been delivered and acknowledged.\n• Ensure any outstanding or expired training has been risk‑assessed and either completed or raised as a Qualification.', 'Ops Team Lead', 'Mtce Mgr. Static, Mtce Mgr. Rotating, Mtce Mgr. Instrument, Mtce Mgr. Elect, Site Engr., Ops Team Lead', 6, true, 1),
('1219119f-fd54-4306-a0cf-ed1ee3513955', 'Procedures', 'Are the Initial Start‑Up and Normal Operating Procedures approved for use and formally handed over to the Asset?', E'Initial Start-Up Procedures\nNormal Operating Procedures', E'• Verify that all Initial Start‑Up, Normal Operating, and related system operating procedures have been fully developed, technically reviewed, and approved.\n• Confirm that the procedures reflect the final as‑built design and commissioning scope.\n• Ensure the approved procedures have been formally handed over to the Asset.', 'Ops Team Lead', 'Process TA2, PACO TA2, Elect TA2, Static TA2, Rotating TA2, Site Engr., Ops Team Lead', 7, true, 1),
('1219119f-fd54-4306-a0cf-ed1ee3513955', 'Alarms', 'Has the Variable Table been updated and implemented, and have all inhibited alarms been reactivated?', 'Variable Table', E'• Verify that all Variable Table limits and parameters have been updated and implemented in the DCS.\n• Confirm that all inhibited, disabled, shelved, or bypassed alarms have been reviewed and returned to service.\n• Ensure alignment between the updated Variable Table, Master Alarm Database (MAD), and actual DCS configuration.', 'Ops Team Lead', 'PACO TA2, Mtce Mgr. Instrument, Site Engr., Ops Team Lead', 8, true, 1),
('1219119f-fd54-4306-a0cf-ed1ee3513955', 'Isolations', 'Have all process and electrical isolations been reviewed, confirmed safe, and verified as correctly in place?', 'Isolation Register', E'• Verify that all process, Instrument and electrical isolations have been reviewed, field‑checked, and confirmed to be correctly applied.\n• Ensure all required isolations necessary to safely introduce hydrocarbons are in place and correctly documented.\n• Confirm that isolation status poses no safety or operational risk.', 'Ops Team Lead', 'Mtce Mgr. Static, Mtce Mgr. Rotating, Mtce Mgr. Instrument, Mtce Mgr. Elect, Site Engr., Ops Team Lead', 9, true, 1),
('1219119f-fd54-4306-a0cf-ed1ee3513955', 'LOLC', 'Has the Locked Open / Locked Closed (LOLC) register been fully updated and verified in the field?', 'LOLC Register', E'• Confirm the LO/LC register is fully updated with all valves designated as Locked Open or Locked Closed.\n• Verify valve positions in the field by physically checking each LO/LC valve against the register.\n• Ensure all anomalies are resolved or escalated.', 'Ops Team Lead', 'Site Engr., Ops Team Lead', 10, true, 1),
('1219119f-fd54-4306-a0cf-ed1ee3513955', 'Temp Equipment', 'Have all Temporary Equipment items been removed from site, or—where still required—been certified and recorded in the Temporary Equipment Register?', 'Temp Equipment Register', E'• Verify that all Temporary Equipment has been removed from the facility unless explicitly required for start‑up or ongoing operations.\n• Confirm that any Temporary Equipment still in service is fully certified, fit‑for‑purpose, and entered into the Temporary Equipment Register.\n• Ensure all anomalies, expired certificates, or undocumented items are resolved.', 'Ops Team Lead', 'BFM Lead, Mtce Mgr. Static, Mtce Mgr. Rotating, Mtce Mgr. Instrument, Mtce Mgr. Elect, Site Engr., Ops Team Lead', 11, true, 1),
('1219119f-fd54-4306-a0cf-ed1ee3513955', 'House Keeping', 'Have all combustible materials, temporary piping, scaffolding materials, and shutdown materials been fully removed from site?', NULL, E'• Verify that all combustible or flammable materials, temporary piping, hoses, scaffolding components, construction debris, and surplus shutdown materials have been removed from the process area.\n• Confirm the site has been cleared and restored to normal operating condition.\n• Perform a physical field walk‑down to ensure no remaining materials pose a hazard.', 'Ops Team Lead', 'BFM Lead, Mtce Mgr. Static, Mtce Mgr. Rotating, Mtce Mgr. Instrument, Mtce Mgr. Elect, Site Engr., Ops Team Lead', 12, true, 1),
('1219119f-fd54-4306-a0cf-ed1ee3513955', 'Vent, Drains & Sewers', 'Have all vent and drain checks been completed—confirming drains, vents, plugs, and caps are correctly installed—and are all sewers uncovered and free of debris?', NULL, E'• Verify that all drain and vent points are intact and correctly fitted with the required plugs, caps, or connections.\n• Confirm that all open drains, channels, and sewers are uncovered, unobstructed, and free from debris.\n• Ensure a physical field walk‑down has been performed.', 'Ops Team Lead', 'Mtce Mgr. Static, Site Engr., Ops Team Lead', 13, true, 1),
('1219119f-fd54-4306-a0cf-ed1ee3513955', 'Start-Up Org', 'Is the start‑up organization fully defined, adequately resourced, and supported by the required specialist vendors?', 'SU Organization Chart', E'• Verify that the full start‑up organisation structure is defined and resourced.\n• Confirm that all required specialist vendors are mobilised, available, and contracted to support start‑up.\n• Ensure that all start‑up personnel and vendors have completed required training, site inductions, and system familiarisation.', 'Ops Team Lead', 'BFM Lead, Site Engr., Ops Team Lead', 14, true, 1),
('1219119f-fd54-4306-a0cf-ed1ee3513955', 'Communication', 'Have all affected units and departments been notified of the planned start‑up activities?', 'SU Notification email', E'• Confirm that all impacted teams have received formal notification of start‑up timing, scope, SIMOPS implications, and operational constraints.\n• Verify that cross‑functional coordination has taken place.\n• Ensure communication has been documented and acknowledged.', 'Ops Team Lead', 'Site Engr., Ops Team Lead', 15, true, 1),
('1219119f-fd54-4306-a0cf-ed1ee3513955', 'Incidence', 'Has a detailed assessment of the incident or equipment failure been completed, with all actions closed or fully mitigated?', 'RCA Report', E'• Verify that the incident or equipment failure has been fully assessed, with root cause, contributing factors, and required mitigations identified.\n• Confirm all corrective actions are closed, risk‑assessed, or formally mitigated.\n• Ensure the findings and mitigations have been cascaded to relevant teams.', 'Ops Team Lead', 'Process TA2, PACO TA2, Elect TA2, Static TA2, Rotating TA2, Tech Safety TA2, MCI TA2, Civil TA2, Site Engr., Ops Team Lead, Ops HSE Adviser', 16, true, 1);

-- Insert Management Systems items (category: 171dd3b3-51b5-4890-b164-afda1b7e827e)
INSERT INTO public.pssr_checklist_items (category, topic, description, supporting_evidence, guidance_notes, responsible, approvers, sequence_number, is_active, version) VALUES
('171dd3b3-51b5-4890-b164-afda1b7e827e', 'CMMS', 'Has the Asset Register, Preventive Maintenance (PM) routines, and Bills of Materials (BOMs) been fully built, validated, and loaded into the CMMS?', 'ARB, PM and BOM Report', E'• Ensure the Asset Register, PM routines, and BOMs are fully developed, quality‑checked, and aligned with engineering deliverables.\n• Verify that all data has been validated and successfully loaded into the CMMS.\n• Confirm that any gaps or outstanding items have been risk‑assessed and raised as Qualifications.', 'BFM Project Engr', 'Mtce Mgr. Static, Mtce Mgr. Rotating, Mtce Mgr. Instrument, Mtce Mgr. Elect, Central Mtce Lead', 1, true, 1),
('171dd3b3-51b5-4890-b164-afda1b7e827e', 'CMMS', 'Have all applicable Preventive Maintenance (PM) routines been fully activated in the CMMS?', 'PM Scheduling Report', E'• Verify that all applicable PM routines have been activated in the CMMS, correctly linked to equipment tags and aligned with the approved maintenance strategy.\n• Confirm that activation includes scheduling, resource requirements, materials/BOM associations, and SCE‑related PMs.\n• Ensure any unactivated or deferred PM routines are reviewed, risk‑assessed, and raised as Qualifications.', 'BFM Project Engr', 'Mtce Mgr. Static, Mtce Mgr. Rotating, Mtce Mgr. Instrument, Mtce Mgr. Elect, Central Mtce Lead', 2, true, 1),
('171dd3b3-51b5-4890-b164-afda1b7e827e', 'IMS', 'Is the Integrity Management System (IMS/PLSS) updated to reflect the additional scope and activated?', 'IMS/ PLSS Report', E'• Ensure the IMS/PLSS is fully updated with all new or modified assets, including corrosion loops, degradation mechanisms, inspection requirements, and risk rankings.\n• Verify that all integrity and corrosion management workflows are activated.\n• Confirm that any gaps or outstanding updates have been reviewed and risk‑assessed.', 'BFM Project Engr', 'MCI TA2, Mtce Mgr. Static, Central Mtce Lead', 3, true, 1),
('171dd3b3-51b5-4890-b164-afda1b7e827e', 'FSR', 'Is the Facility Status Report (FSR) or similar, updated to reflect the integrity status of the new or modified facility?', 'FSR Dashboard screen shot', E'• Ensure the FSR tool is fully updated to reflect the latest integrity status of the new or modified facility.\n• Verify that all integrity‑related data is accurate, complete, and aligned with supporting documentation.\n• Confirm that any outstanding issues are clearly captured in the FSR.', 'BFM Project Engr', 'Central Mtce Lead', 4, true, 1),
('171dd3b3-51b5-4890-b164-afda1b7e827e', 'Operational Registers', 'Are all Operational Registers fully updated, accurate, and verified?', 'Operational Registers', E'• Verify that all operational registers are fully updated to reflect current field conditions.\n• Confirm that each register has undergone the required physical verification and review.\n• Ensure that all related Management of Change, work requests, audits, and documentation updates have been completed.', 'Ops Team Lead', 'Site Engr., Ops Team Lead', 5, true, 1),
('171dd3b3-51b5-4890-b164-afda1b7e827e', 'Logsheets', 'Are the Operator Logsheets updated to reflect the current scope and available for use?', 'Operator Logsheets', E'• Verify that the Operator Logsheets have been updated to include all parameters, limits, and tasks associated with the new or modified facility.\n• Confirm that logsheets are available at the point of use and reflect the latest monitoring frequencies.\n• Ensure any changes have been incorporated and operators have been briefed.', 'Ops Team Lead', 'Site Engr., Ops Team Lead', 6, true, 1);

-- Insert HSE items (category: 05d1aba6-fc5a-40fa-bc50-9f0bebec0331)
INSERT INTO public.pssr_checklist_items (category, topic, description, supporting_evidence, guidance_notes, responsible, approvers, sequence_number, is_active, version) VALUES
('05d1aba6-fc5a-40fa-bc50-9f0bebec0331', 'Emergency Response', 'Have Emergency Response (ER) Teams been notified of the start‑up, and are they fully resourced and equipped to respond?', 'Email confirmation from ERT Lead', E'• Verify that the Emergency Response Team has been formally notified of the planned start‑up.\n• Confirm that the ER Team is fully staffed, competent, and available.\n• Ensure all ER equipment is in service and ready, including firefighting equipment, rescue tools, communication systems, and breathing apparatus.', 'Ops Team Lead', 'ER Adviser', 1, true, 1),
('05d1aba6-fc5a-40fa-bc50-9f0bebec0331', 'Site Access', 'Have Site Access Controls been fully implemented, and have all prerequisites for safe site access been fully met?', NULL, E'• Verify that full Site Access Control measures are in place, ensuring only personnel who have completed the mandatory site‑specific HSE induction are allowed into process areas.\n• Confirm safe‑access prerequisites are provided and used, including escape respirators, Personal Gas Monitors, and required PPE.\n• Ensure site‑control rules are enforced.', 'Ops Team Lead', 'Site Engr., Ops Team Lead, Ops HSE Adviser', 2, true, 1),
('05d1aba6-fc5a-40fa-bc50-9f0bebec0331', 'Site Access', 'Are all Escape Routes clearly marked and free of obstruction?', NULL, E'• Verify that all designated escape routes and emergency pathways are clearly marked and visible.\n• Confirm escape routes are fully free of obstructions.\n• Ensure personnel are familiar with escape routing as part of the site‑specific HSE induction.', 'Ops Team Lead', 'Site Engr., Ops Team Lead, Ops HSE Adviser', 3, true, 1),
('05d1aba6-fc5a-40fa-bc50-9f0bebec0331', 'Fire & Safety Audit', 'Has a Fire & Safety Audit been completed with all actions closed out, and are all safety‑critical equipment correctly located and in service?', 'Fire Audit Report', E'• Verify that a Fire & Safety audit or inspection has been conducted and all outstanding actions are closed.\n• Confirm all safety equipment is in service and correctly located, including fire extinguishers, firewater/monitor systems, safety showers, eyewash stations, spill kits.\n• Ensure emergency equipment supports ER team capability.', 'Ops Team Lead', 'Site Engr., Ops Team Lead, Ops HSE Adviser', 4, true, 1);
