
-- Phase 1: Create table
CREATE TABLE public.agent_foundation_knowledge (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_code text,
  document_type text,
  template_type text NOT NULL,
  title text NOT NULL,
  knowledge_card jsonb,
  prompt_fragment text,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.agent_foundation_knowledge ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users read foundation knowledge"
  ON public.agent_foundation_knowledge FOR SELECT
  TO authenticated
  USING (true);

-- Phase 2: Seed 7 foundation records with explicit UUIDs

-- Record 1: Universal P&ID knowledge
INSERT INTO public.agent_foundation_knowledge (id, agent_code, document_type, template_type, title, sort_order, knowledge_card)
VALUES (
  'a1b2c3d4-0001-4000-8000-000000000001',
  NULL, NULL, 'knowledge',
  'P&ID Universal Literacy — ISA 5.1 and Oil & Gas Practice',
  1,
  '{
    "core_facts": [
      {"statement": "A P&ID (Piping and Instrumentation Diagram) — also called PEFS (Process Engineering Flow Scheme) in Shell/BP convention — shows every piece of process equipment, all piping with size and fluid codes, all instruments, all control loops, all valves and their positions, and all safety devices. It is used for design, construction, commissioning, HAZOP, MOC, operations, and maintenance.", "confidence": "high", "tags": ["P&ID","PEFS","definition","lifecycle"]},
      {"statement": "Drawing hierarchy: BFD (Block Flow Diagram) — process concept only; PFD (Process Flow Diagram) — major equipment, main streams, key conditions; P&ID — everything needed to build and operate, including all instruments, loops, valves, pipe sizes and classes.", "confidence": "high", "tags": ["BFD","PFD","P&ID","hierarchy"]},
      {"statement": "Drawing status controls usage: IFR=Issued for Review (do not build from); IFC=Issued for Construction (preliminary); AFC=Approved for Construction (definitive); AFU=Approved for Use (operational). Only AFC or AFU drawings are authoritative for construction, commissioning, or HAZOP.", "confidence": "high", "tags": ["drawing status","AFC","AFU","document control"]},
      {"statement": "The legend sheet (lead sheet) defines all symbols, line types, bubble location conventions, and project-specific deviations from ISA 5.1. It MUST be read before any other P&ID sheet in a drawing package. Reading a P&ID without the legend sheet is unreliable.", "confidence": "high", "tags": ["legend sheet","lead sheet","ISA 5.1","symbol library"]},
      {"statement": "ISA 5.1 FIRST LETTER — measured variable: A=Analysis, C=Conductivity(user), D=Density(user), E=Voltage/Element, F=Flow, H=Hand/Manual, I=Current(electrical), J=Power, K=Time, L=Level, M=Moisture(user), P=Pressure/Vacuum, Q=Quantity, R=Radiation, S=Speed/Frequency, T=Temperature, U=Multivariable, V=Vibration, W=Weight/Force, X=Unclassified, Y=Event/State, Z=Position/Dimension.", "confidence": "high", "tags": ["ISA 5.1","first letter","measured variable","tag identification"]},
      {"statement": "ISA 5.1 SUBSEQUENT LETTERS — function: A=Alarm, C=Control, D=Differential(modifier), E=Element(primary), H=High(modifier), I=Indicate, K=Control Station, L=Low(modifier), M=Middle/Intermediate, O=Orifice/Restriction, P=Point(Test), Q=Integrate/Totalize, R=Record, S=Switch, T=Transmit, V=Valve/Damper/Louver, W=Well/Thermowell, X=Unclassified, Y=Relay/Compute/Convert, Z=Driver/Actuator. CRITICAL: T as first letter = Temperature; T as subsequent letter = Transmit. TT = Temperature Transmitter.", "confidence": "high", "tags": ["ISA 5.1","subsequent letters","function","transmit","temperature distinction"]},
      {"statement": "Common tag combinations: FT=Flow Transmitter, FIC=Flow Indicating Controller, FV=Flow Control Valve, PT=Pressure Transmitter, PIC=Pressure Indicating Controller, PSV=Pressure Safety Valve, PSH=Pressure Switch High, PSHH=Pressure Switch High-High (trip), PAH=Pressure Alarm High, PAHH=Pressure Alarm High-High, TT=Temperature Transmitter, TIC=Temperature Indicating Controller, LT=Level Transmitter, LIC=Level Indicating Controller, LV=Level Control Valve, LSHH=Level Switch High-High (ESD trip), LAH=Level Alarm High, FE=Flow Element (primary element, e.g. orifice plate).", "confidence": "high", "tags": ["tag combinations","FT","PT","TT","LT","PSV","PSHH","LSHH"]},
      {"statement": "Instrument bubble location indicator: PLAIN CIRCLE (no line) = field-mounted near the process. CIRCLE + SINGLE SOLID LINE = primary control room, DCS, operator accessible. CIRCLE + SINGLE DASHED LINE = secondary/local panel, not normally operator-accessible. CIRCLE + DOUBLE LINE = behind panel, inaccessible. SQUARE or RECTANGLE = shared display/control (DCS screen). DIAMOND = computer/PLC function.", "confidence": "high", "tags": ["instrument bubble","location indicator","field","control room","DCS","local panel"]},
      {"statement": "P&ID line type conventions (check legend sheet for project-specific deviations): THICK SOLID = main process piping. THIN SOLID = instrument connection/tubing. DASHED SINGLE = electrical signal (4-20mA). DOUBLE DASHED or DOT-DASH = pneumatic signal (3-15 psig instrument air). DOTTED = hydraulic signal. THICK SHORT DASHES = software/data link (DCS internal bus).", "confidence": "high", "tags": ["line types","electrical signal","pneumatic signal","process piping","data link"]},
      {"statement": "Line designation format: [Nominal Size]-[Fluid Service Code]-[Pipe Class]-[Sequential Number]-[Insulation Code]. Example: 4-GP-A1B-3045-HT = 4 inch, Gas Process, ASME 150lb carbon steel, line 3045, heat traced. Common fluid codes: GP=Gas Process, LP=Liquid Process, HC=Hydrocarbons, SW=Sea Water, FW=Fresh Water, IA=Instrument Air, PA=Plant Air, N2=Nitrogen, SS=Sour Service.", "confidence": "high", "tags": ["line designation","line number","pipe class","fluid code","nominal size"]},
      {"statement": "Control loop anatomy — every control loop has: PRIMARY ELEMENT (converts process variable to signal: orifice plate FE, thermowell TE, dp cell) → TRANSMITTER (sends 4-20mA to DCS: FT, TT, PT, LT) → CONTROLLER (compares measurement to setpoint, calculates output: FIC, TIC, PIC, LIC) → FINAL CONTROL ELEMENT (acts on process: control valve FV/TV/LV, or motor). All elements in one loop share the same loop number.", "confidence": "high", "tags": ["control loop","primary element","transmitter","controller","final control element","loop number"]},
      {"statement": "Control valve bypass arrangement — standard P&ID feature: upstream block valve (gate or ball, normally open) → control valve → downstream block valve (normally open). Bypass line with globe/needle valve (normally closed) allows manual control during maintenance. Drain valve at low point of bypass loop. This U-shape arrangement is shown on P&IDs around every control valve.", "confidence": "high", "tags": ["control valve","bypass","block valve","normally open","normally closed","maintenance isolation"]},
      {"statement": "Valve operating position notation: NO=Normally Open (open during normal operation), NC=Normally Closed (closed during normal operation). Fail position notation: FO=Fail Open (valve opens on loss of instrument air/power), FC=Fail Closed, FL=Fail Locked (stays in last position). NO and FC can apply to the same valve simultaneously — it is normally open but closes on air failure.", "confidence": "high", "tags": ["NO","NC","normally open","normally closed","FO","FC","FL","fail position"]},
      {"statement": "PSV (Pressure Safety Valve) on a P&ID: shown as angle valve with perpendicular spring symbol. Inlet = process connection. Outlet MUST connect to flare header, vent stack, or closed drain system — never dead-ended. Set pressure annotated on P&ID (e.g. SET=750 psig). Pilot-operated PSV shows pilot symbol connected to main body. Rupture disc (RD) may be shown upstream of PSV — burst pressure annotated.", "confidence": "high", "tags": ["PSV","PRV","set pressure","flare","relief system","rupture disc","pilot operated"]},
      {"statement": "Spectacle blind: two circles connected by a bar — solid disc (blinded position) and hollow ring (open position). Solid disc facing the equipment = isolated. Hollow ring facing = flow path open. Spade = single solid disc for temporary maintenance isolation. Spacer = single hollow ring replacing spade when line is reinstated. Normal operating position is shown on the AFC P&ID.", "confidence": "high", "tags": ["spectacle blind","spade","spacer","positive isolation","maintenance isolation"]},
      {"statement": "ESD (Emergency Shutdown) system on P&IDs: ESD/SDV valves shown with distinctive actuator and ESD logic system reference tag (e.g. ESD-1, F&G-2). High-high and Low-Low switch tags (PSHH, LSHH, TAHH, TSLL) feed the SIS trip logic. SIS/SIL-rated instruments shown with distinct bubble style (diamond or double outline) — physically and electrically segregated from DCS. All safety loops reference a Cause and Effect matrix for trip conditions.", "confidence": "high", "tags": ["ESD","SDV","SIS","SIL","PSHH","LSHH","cause and effect","safety trip","segregation"]},
      {"statement": "Continuation arrows (match lines / break arrows): process lines continuing to another sheet show an arrow with destination drawing number. Lines arriving from another sheet show an arrow with source drawing number. ALWAYS follow these to adjacent sheets before concluding a line is terminated. Missing match line reference = P&ID deficiency requiring TQ.", "confidence": "high", "tags": ["continuation arrow","match line","cross-reference","adjacent sheet","TQ"]},
      {"statement": "Three-phase separator P&ID — typical instrument loop layout: water boot level controlled by LT/LC/LV (level transmitter, level controller, level control valve on water outlet). Oil level in oil section controlled by second LT/LC/LV (oil outlet). Gas cap pressure controlled by PT/PIC/PCV on gas outlet. LSHH on vessel body trips ESD to isolate vessel. PAHH/LSHH alarms to control room. PSV on vessel top connected to flare. Temperature TI on inlet (indication only, no control). This is the most common P&ID in upstream oil and gas.", "confidence": "high", "tags": ["three-phase separator","level control","pressure control","LT","LV","PCV","PSV","LSHH","oil gas water"]}
    ],
    "procedures": [
      {"name": "10-step P&ID reading method", "steps": ["1. Check title block: project, drawing number, revision letter. Verify revision against DMS/Assai. Do not use a superseded revision for any safety-critical activity.", "2. Read the legend sheet for this package before any P&ID sheet. Note non-standard symbols, line type conventions, bubble codes, and tag numbering format.", "3. Identify drawing boundary: read all continuation arrows and match lines. Know what enters and exits this sheet.", "4. Identify all equipment: tag numbers (V=vessel, P=pump, E=exchanger, K=compressor, T=column, H=heater) and brief description.", "5. Trace main process flow following arrowheads. Note pipe sizes from line designations and fluid service codes.", "6. Identify branch connections: drain (D), vent (V), sample (SC), bypass lines, utility connections (steam, N2, CW, IA).", "7. For each instrument bubble: decode tag letters by ISA table. Note bubble type (location). Trace signal lines to find the complete control loop.", "8. Identify all safety devices: PSVs (confirm discharge route), ESD/SDV valves (note trip condition), PSHH/LSHH switches (note setpoints if shown), SIS instruments (distinct bubble).", "9. Identify all isolation points: spectacle blinds (note normal position), double-block-and-bleed arrangements, spades.", "10. Check for revision clouds (changed areas), holds (TBD), notes referencing TQs or DCRs."], "tags": ["P&ID reading","systematic method","legend sheet","control loop","safety devices","revision cloud"]},
      {"name": "Decoding an instrument tag number", "steps": ["1. First letter = measured variable (F=Flow, P=Pressure, T=Temperature, L=Level, A=Analysis, etc.).", "2. Subsequent letters up to the first digit = functional modifiers. Apply ISA subsequent-letter table to each.", "3. Apply critical rule: T as first letter = Temperature. T as subsequent letter = Transmit. So FT=Flow Transmitter, TT=Temperature Transmitter, TC=Temperature Controller.", "4. Loop number (digits) = groups all instruments working together. FT-3045, FIC-3045, FV-3045 are all in loop 3045.", "5. Suffix letters (A, B) = duplicate instruments in same loop. Slash suffix (FT-3045/1) = sub-element or channel.", "6. Bubble type = physical location. Build the full description: FIC-3045 = Flow Indicating Controller, loop 3045, primary control room (DCS), operator accessible."], "tags": ["tag decoding","ISA letters","loop number","bubble type","instrument identification"]},
      {"name": "Tracing a complete control loop", "steps": ["1. Find the final control element (control valve or motor) — the output end of the loop.", "2. Read the control valve tag and fail position (FC/FO/FL).", "3. Follow the signal line (dashed = electrical) from the valve back to the controller bubble (FIC, TIC, PIC, LIC in DCS).", "4. Follow the signal line from the controller to the transmitter (FT, TT, PT, LT — field-mounted, plain circle bubble).", "5. Look for a primary element upstream of the transmitter (FE = orifice, TE = thermowell, LE = float/dp cell).", "6. Check for I/P converter between controller and valve: controller (4-20mA electrical) → TY/FY (I/P converter) → pneumatic 3-15 psig → valve actuator.", "7. Check for cascade: outer loop controller setpoint drives inner loop controller setpoint.", "8. Document: FE-3045 (orifice in 4-GP-A1B-3045) → FT-3045 (field 4-20mA) → FIC-3045 (DCS) → FY-3045 (I/P) → FV-3045 (pneumatic globe valve, FC, 4-inch)."], "tags": ["control loop","tracing","primary element","I/P converter","cascade","loop documentation"]}
    ],
    "entities": [
      {"term": "P&ID / PEFS / PFS", "definition": "Piping and Instrumentation Diagram / Process Engineering Flow Scheme / Process Flow Scheme — same document type, different company naming conventions. Shell and BP use PEFS/PFS. Most other companies use P&ID.", "related_terms": ["EFD","MFD","SFD","BFD","PFD"]},
      {"term": "ISA 5.1", "definition": "ANSI/ISA-5.1-2024 — the international standard governing instrumentation symbols, identification letter combinations, tag number structures, and signal conventions used in all P&IDs.", "related_terms": ["ISO 10628","BS 5070","tag number"]},
      {"term": "Legend sheet / lead sheet", "definition": "First drawing in a P&ID package defining all symbols, line types, bubble conventions, and project-specific deviations from ISA 5.1.", "related_terms": ["symbol library","drawing package","ISA 5.1"]},
      {"term": "AFC / AFU", "definition": "Approved for Construction / Approved for Use — the only drawing statuses authoritative for construction, commissioning, HAZOP, or field work.", "related_terms": ["drawing status","document control","DMS"]},
      {"term": "Control loop", "definition": "Complete measurement-control-actuation circuit sharing one loop number: primary element → transmitter → controller → final control element.", "related_terms": ["PID controller","transmitter","control valve","setpoint","cascade"]},
      {"term": "Fail position (FO/FC/FL)", "definition": "Position a control valve moves to on loss of instrument air or power. FO=Fail Open, FC=Fail Closed, FL=Fail Locked.", "related_terms": ["control valve","ESD","spring return","instrument air"]},
      {"term": "PSV / PRV", "definition": "Pressure Safety Valve / Pressure Relief Valve — self-actuating valve opening when process pressure exceeds set pressure. Discharge must go to flare, safe vent, or contained system.", "related_terms": ["set pressure","overpressure","flare","rupture disc","pilot PSV"]},
      {"term": "ESD / SDV", "definition": "Emergency Shutdown / Shutdown Valve — tripped closed or open by the Safety Instrumented System on hazardous conditions.", "related_terms": ["SIS","SIL","interlock","PSHH","LSHH","cause and effect"]},
      {"term": "SIS / SIL", "definition": "Safety Instrumented System / Safety Integrity Level. SIS = independent safety control system, physically segregated from DCS. SIL = reliability rating (1-4).", "related_terms": ["ESD","SDV","functional safety","IEC 61511"]},
      {"term": "Spectacle blind", "definition": "Maintenance isolation device: two circles (solid disc + hollow ring) connected by bar. Solid disc facing equipment = blinded/isolated.", "related_terms": ["spade","spacer","positive isolation","blind flange"]},
      {"term": "Line designation", "definition": "Alphanumeric code on a process line encoding pipe size, fluid service, material class, and sequential number.", "related_terms": ["pipe class","fluid service","nominal bore","insulation code"]}
    ],
    "decision_rules": [
      {"condition": "A P&ID drawing is not AFC or AFU status", "action": "Do not use for construction, commissioning, or HAZOP. Request current AFC revision from Document Controller.", "priority": "critical", "tags": ["drawing status","AFC"]},
      {"condition": "Control valve fail position is not shown or annotated on the P&ID", "action": "Flag as P&ID deficiency. Raise TQ to responsible engineer. Do not assume fail position — it is safety critical.", "priority": "critical", "tags": ["fail position","TQ","control valve"]},
      {"condition": "A PSV on the P&ID has no discharge route shown", "action": "Flag as potential P&ID omission. Verify continuation drawing. Raise TQ if no discharge route found.", "priority": "critical", "tags": ["PSV","flare","discharge route"]},
      {"condition": "An instrument tag appears on a P&ID but has no corresponding record in the completions management system", "action": "Flag for Completions Engineer. Either data error (instrument not registered) or engineering error (unregistered instrument). Resolve before commissioning that loop.", "priority": "high", "tags": ["instrument tag","completions","data integrity"]},
      {"condition": "The P&ID revision on a physical drawing does not match the revision in the DMS", "action": "The DMS revision is authoritative. Retrieve current AFC revision before proceeding with any safety-critical activity.", "priority": "high", "tags": ["revision","DMS","document control","Assai"]},
      {"condition": "Field installation does not match what is shown on the AFC P&ID", "action": "Raise punch list item (Cat A if safety or test-critical, Cat B otherwise). Red-line the P&ID. Do not accept the subsystem until discrepancy resolved by field correction or revised P&ID via TQ/DCR.", "priority": "critical", "tags": ["field discrepancy","punch list","red-line","walkdown"]}
    ]
  }'::jsonb
) ON CONFLICT (id) DO NOTHING;

-- Record 2: Fred commissioning knowledge
INSERT INTO public.agent_foundation_knowledge (id, agent_code, document_type, template_type, title, sort_order, knowledge_card)
VALUES (
  'a1b2c3d4-0002-4000-8000-000000000002',
  'fred', NULL, 'knowledge',
  'P&ID Reading for Commissioning Engineers',
  2,
  '{
    "core_facts": [
      {"statement": "The LOSH (Limits of System Handover) drawing is a P&ID with red boundary lines marking where one subsystem ends and another begins. The commissioning engineer draws these boundaries considering: testability (each subsystem must be independently pressure-testable), commissioning priority (utilities before process), and construction sequence. The LOSH is the primary input to the GoCompletions database population.", "confidence": "high", "tags": ["LOSH","systemisation","subsystem boundary","GoCompletions","commissioning"]},
      {"statement": "A-ITR types are determined by equipment type shown on the P&ID. Every tagged item on the P&ID generates one or more ITRs in the completions management system. A pump on the P&ID generates BGC-M02A. A pressure vessel generates BGC-M01A. An instrument cable generates BGC-I16A. An instrument (transmitter) generates BGC-I01A plus BGC-I02B for loop check. The P&ID is the definitive source for what ITRs are required.", "confidence": "high", "tags": ["A-ITR","B-ITR","ITR allocation","equipment type","GoCompletions","loop check"]},
      {"statement": "Before a commissioning walkdown, use the P&ID to prepare a field verification checklist: every tagged instrument must be physically present and correctly installed; every valve must be in the correct position (NO or NC as annotated); every spectacle blind must be in the correct position; every line must match the line designation on the P&ID; any field deviations are red-lined on a copy of the P&ID and raised as punch items.", "confidence": "high", "tags": ["walkdown","pre-commissioning","field verification","red-line","punch list"]},
      {"statement": "Test pack boundaries for piping pressure tests are defined using P&IDs. Natural test pack limits are spectacle blinds and isolation valves. One test pack typically covers one or more subsystems as defined in the LOSH. The test pressure and fluid (typically water for hydrotest, nitrogen for pneumatic test) must be compatible with the equipment and instruments shown in the test pack boundary — sensitive instruments (transmitters) must be isolated before pressurisation.", "confidence": "high", "tags": ["test pack","pressure test","hydrotest","spectacle blind","instrument isolation","commissioning"]},
      {"statement": "Instrument loop checking (B-ITR BGC-I02B) uses the P&ID to confirm: loop number, transmitter tag and location, controller tag in DCS, final control element tag and fail position. The loop check verifies end-to-end signal continuity: field instrument output (4-20mA) must appear correctly at the DCS input; DCS controller output must drive the control valve to the correct position; fail position must be confirmed by isolating instrument air.", "confidence": "high", "tags": ["loop check","B-ITR","I02B","4-20mA","DCS","fail position test"]},
      {"statement": "Control valve function testing during pre-commissioning (B-ITR BGC-M51B): confirm valve tag, fail position (FO/FC/FL), normal operating position (NO/NC), stroke test from DCS (0% to 100% and back), verify positioner calibration, confirm actuator travels smoothly with no mechanical binding, confirm block valve positions upstream and downstream, record any stiction or hunting. All results signed off on the ITR.", "confidence": "high", "tags": ["control valve","function test","stroke test","positioner","B-ITR","M51B"]}
    ],
    "procedures": [
      {"name": "LOSH boundary marking on a P&ID", "steps": ["1. Start from the main process flow line. Identify natural break points: isolation valves, spectacle blinds, flanged connections, vessel nozzles.", "2. Consider testability: each subsystem must be independently pressure-testable without affecting adjacent subsystems.", "3. Consider commissioning priority: utilities (instrument air, nitrogen, cooling water) should be in separate early-commission subsystems from main process.", "4. Consider construction sequence: equipment completed earliest should be in first-priority subsystems.", "5. Draw boundary on a copy of the P&ID in red. Mark IN items and OUT items for the subsystem.", "6. Assign a subsystem reference number aligned with the project WBS and GoCompletions structure.", "7. Review with Construction Lead and Pre-Comm/CSU Lead before freezing.", "8. Issue as an official LOSH drawing — this becomes a controlled document in the DMS."], "tags": ["LOSH","systemisation","subsystem","boundary","GoCompletions","construction sequence"]}
    ],
    "decision_rules": [
      {"condition": "A tag number exists in GoCompletions but cannot be found on the current AFC P&ID", "action": "Data integrity issue. Either instrument removed by DCR (GoCompletions not updated) or wrong P&ID revision in hand. Freeze commissioning of that instrument until resolved.", "priority": "critical", "tags": ["GoCompletions","P&ID","DCR","data integrity"]},
      {"condition": "Field installation does not match the P&ID (valve type, instrument missing, line routing different)", "action": "Raise punch list item (Cat A if safety/test-critical, Cat B otherwise) and red-line the P&ID copy. Do not accept the subsystem until discrepancy is resolved.", "priority": "critical", "tags": ["punch list","red-line","field discrepancy"]},
      {"condition": "A sensitive instrument (transmitter, analyser) is within a test pack boundary that will be pressure tested", "action": "Isolate the instrument before pressurisation using its root valve. Do NOT pressure test through a live transmitter — overpressure will destroy the sensor diaphragm.", "priority": "critical", "tags": ["hydrotest","instrument isolation","root valve","transmitter protection"]}
    ]
  }'::jsonb
) ON CONFLICT (id) DO NOTHING;

-- Record 3: Ivan technical authority knowledge
INSERT INTO public.agent_foundation_knowledge (id, agent_code, document_type, template_type, title, sort_order, knowledge_card)
VALUES (
  'a1b2c3d4-0003-4000-8000-000000000003',
  'ivan', NULL, 'knowledge',
  'P&ID Reading for Technical Authority — HAZOP and Safety Review',
  3,
  '{
    "core_facts": [
      {"statement": "P&IDs are the primary document for HAZOP (Hazard and Operability Study). The HAZOP team works through the P&ID node by node applying guide words (No, More, Less, Reverse, Other Than, As Well As, Part Of) to process parameters (Flow, Pressure, Temperature, Level, Composition, Reaction) to identify credible hazardous deviations. No P&ID = no HAZOP. A HAZOP cannot be completed on an outdated or IFC drawing — it must be the current AFC revision.", "confidence": "high", "tags": ["HAZOP","guide words","deviation","P&ID","AFC"]},
      {"statement": "HAZOP node definition: a node is a section of the P&ID with a defined design intent, typically bounded by isolation points or major equipment items. One vessel = one node. One heat exchanger = one or two nodes (shell side and tube side). One pump with suction and discharge lines = one node. Nodes must be small enough to have a single design intent but large enough to be meaningful.", "confidence": "high", "tags": ["HAZOP","node","design intent","vessel","heat exchanger","pump"]},
      {"statement": "SIL (Safety Integrity Level) assessment: each safety function on the P&ID is assessed against IEC 61508/61511. SIS instruments (distinct bubble style) must be physically and electrically independent from DCS. The SIL rating determines the required probability of failure on demand (SIL 1: 0.1-0.01, SIL 2: 0.01-0.001, SIL 3: 0.001-0.0001). SIL 3 and above require dedicated hardware voting arrangements (typically 2oo3). Verify SIS segregation on the P&ID before approving.", "confidence": "high", "tags": ["SIL","SIS","IEC 61511","voting","segregation","DCS independence"]},
      {"statement": "MOC (Management of Change) is required whenever a process modification changes the P&ID from the HAZOP-studied AFC state. The TA must sign off that the change does not introduce new hazards or invalidate existing safeguards. The P&ID must be updated to the new revision and a targeted HAZOP close-out review conducted for the changed node. Verbal agreements to change P&IDs without formal MOC are not acceptable.", "confidence": "high", "tags": ["MOC","management of change","HAZOP closeout","TA sign-off","P&ID revision"]}
    ],
    "procedures": [
      {"name": "HAZOP node review using P&ID", "steps": ["1. Define the HAZOP node boundary on the P&ID — typically between two isolation points or across one major equipment item.", "2. State the design intent: what this node does under normal conditions.", "3. For each process parameter relevant to the node, apply each guide word: No Flow, More Flow, Less Flow, Reverse Flow; More Pressure, Less Pressure; More Temperature, Less Temperature; More Level, Less Level; etc.", "4. For each credible deviation: identify causes, consequences, and existing safeguards shown on the P&ID.", "5. Assess safeguard adequacy. If inadequate: raise HAZOP action item.", "6. Record the HAZOP worksheet: node reference, guide word, parameter, deviation, causes, consequences, safeguards, recommendations.", "7. Review action close-out: each HAZOP action must be formally closed with evidence before the HAZOP is signed off."], "tags": ["HAZOP","node review","guide words","safeguards","action items","worksheet"]}
    ],
    "decision_rules": [
      {"condition": "A P&ID shows a new instrument loop or equipment change that was not in the HAZOP-studied revision", "action": "Require HAZOP close-out review of the changed node before AFC approval. TA cannot sign AFC on a revision adding safety-critical changes without review.", "priority": "critical", "tags": ["HAZOP","P&ID revision","MOC","TA sign-off"]},
      {"condition": "An ESD valve fail position would result in an unsafe condition on the most likely failure scenario", "action": "Raise TQ to process/safety engineer. Change fail position on P&ID and physical valve. This is a safety-critical error blocking AFC approval.", "priority": "critical", "tags": ["ESD","fail position","TQ","safety","AFC"]},
      {"condition": "SIS and DCS instruments appear to share the same wiring or power supply on the P&ID", "action": "Flag as segregation failure. SIS and DCS must be electrically and physically independent. Raise TQ and require engineering correction before AFC.", "priority": "critical", "tags": ["SIS","DCS","segregation","IEC 61511","independence"]}
    ]
  }'::jsonb
) ON CONFLICT (id) DO NOTHING;

-- Record 4: P&ID extraction template
INSERT INTO public.agent_foundation_knowledge (id, agent_code, document_type, template_type, title, sort_order, prompt_fragment)
VALUES (
  'a1b2c3d4-0004-4000-8000-000000000004',
  NULL, 'P&ID', 'extraction',
  'P&ID extraction sections',
  1,
  E'When analysing a P&ID image or document, your structured response MUST include these additional sections after the standard 7 sections:\n\n## Drawing identification\n[Title block details: project name, drawing title, drawing number, revision letter, date]\n\n## System boundary\n[What process system does this P&ID cover? What enters and exits the drawing boundary? Reference continuation drawing numbers.]\n\n## Equipment inventory\n[All tagged equipment: Tag | Type | Brief description. Example: V-3401 | Three-phase separator | 750 psig operating, horizontal vessel]\n\n## Instrumentation inventory\n[All instrument tags: Tag | Function | Location. Example: FT-3045 | Flow transmitter on feed gas line | Field-mounted, 4-20mA to DCS]\n\n## Control loops identified\n[Each loop: Loop number | What it controls | Measurement point → Controller → Final control element | Fail position. Example: Loop 3045: Controls feed gas flow | FE-3045 (orifice) → FT-3045 (field) → FIC-3045 (DCS) → FV-3045 (globe valve, FC)]\n\n## Safety systems\n[PSVs: Tag, set pressure, discharge route. ESD/SDV valves: Tag, trip condition. High-high/low-low switches: Tag, setpoint if shown. SIS loops identified.]\n\n## Isolation points\n[All spectacle blinds (tag if shown, normal position), spades, double-block-and-bleed arrangements. These define maintainable boundaries.]\n\n## Line inventory\n[Primary process lines: designation, size, fluid service, pipe class. Example: 4-GP-A1B-3045 | 4 inch | Gas Process | ANSI 150 carbon steel]'
) ON CONFLICT (id) DO NOTHING;

-- Record 5: P&ID Legend Sheet extraction template
INSERT INTO public.agent_foundation_knowledge (id, agent_code, document_type, template_type, title, sort_order, prompt_fragment)
VALUES (
  'a1b2c3d4-0005-4000-8000-000000000005',
  NULL, 'P&ID Legend Sheet', 'extraction',
  'Legend Sheet extraction sections',
  1,
  E'When analysing a P&ID Legend Sheet, your structured response MUST include these additional sections after the standard 7 sections:\n\n## Symbol library summary\n[Every non-standard or project-specific symbol defined: Symbol name | What it represents | When used]\n\n## Line type conventions\n[Every line type shown: Line style | Represents | Signal type/medium]\n\n## Instrument bubble conventions\n[The location indicator system used on this project: Plain circle = ? | Line through circle = ? | Double line = ? | etc.]\n\n## Tag numbering scheme\n[How tag numbers are structured on this project: format, what each segment means, numbering sequence]\n\n## Deviations from ISA 5.1\n[Any symbol or convention differing from ISA 5.1 standard default — these are critical to understand before reading any P&ID in this package]'
) ON CONFLICT (id) DO NOTHING;

-- Record 6: Fred's commissioning lens
INSERT INTO public.agent_foundation_knowledge (id, agent_code, document_type, template_type, title, sort_order, prompt_fragment)
VALUES (
  'a1b2c3d4-0006-4000-8000-000000000006',
  'fred', 'P&ID', 'lens',
  'Fred''s Commissioning Lens',
  1,
  E'When reading this P&ID, apply a Commissioning Engineer''s lens:\n- Identify where LOSH subsystem boundaries could logically be drawn\n- Note every tagged item and what A-ITR or B-ITR it generates\n- Identify test pack boundaries: which spectacle blinds and isolation valves define a self-contained pressure test boundary?\n- Note all instruments requiring loop checking (B-ITR BGC-I02B)\n- Identify all ESD and safety interlock logic that must be tested before startup\n- Flag any instrument without an isolation root valve (commissioning deficiency)\n- Note all control valve bypass arrangements\n- Identify which instruments must be isolated before a hydrotest\n\nAdd one additional section to your response:\n## Commissioning notes\n[LOSH boundary suggestions, ITR implications, test pack boundaries, potential deficiencies]'
) ON CONFLICT (id) DO NOTHING;

-- Record 7: Ivan's technical authority lens
INSERT INTO public.agent_foundation_knowledge (id, agent_code, document_type, template_type, title, sort_order, prompt_fragment)
VALUES (
  'a1b2c3d4-0007-4000-8000-000000000007',
  'ivan', 'P&ID', 'lens',
  'Ivan''s Technical Authority Lens',
  1,
  E'When reading this P&ID, apply a Technical Authority''s lens:\n- Identify the top 3-5 credible HAZOP deviations for the main process node\n- For each: state the cause, consequence, and existing safeguards shown on this P&ID\n- Verify that all PSVs have a discharge route shown and that the set pressure is annotated\n- Verify that SIS/SIL instruments are visually distinct from DCS instruments\n- Check that all ESD valve fail positions are shown and are the safe direction\n- Check that no SIS and DCS instruments appear to share the same connection point\n- Flag any control valve whose fail position is not annotated (safety deficiency)\n- Note any process changes from adjacent drawings that may require MOC\n\nAdd one additional section to your response:\n## Technical authority notes\n[HAZOP deviation summary, safeguard adequacy assessment, SIS segregation status, open TQ items identified]'
) ON CONFLICT (id) DO NOTHING;
