
-- Insert remaining document types (MX through ZW and remaining disciplines)
INSERT INTO public.dms_document_types (code, document_name, document_description, tier, rlmu, discipline_code, discipline_name, acceptable_status, display_order) VALUES
('780', 'Other Assessment Report', 'Health check, GAP analysis etc.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 409),
('1206', 'Design Calculation', 'Prepared in order to prove that the item meets the design criteria.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 410),
('1380', 'Other Calculation', NULL, NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 411),
('2105', 'Equipment Datasheet', 'Gives precise information about a Tag, Equipment or a Model.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 412),
('2305', 'Assembly Diagram', 'Shows an assembly of equipment components.', NULL, NULL, 'MX', 'Mechanical Other', 'AFC, AFU, AFD', 413),
('2320', 'Equipment Cross Section Diagram', NULL, NULL, NULL, 'MX', 'Mechanical Other', 'AFC, AFU, AFD', 414),
('2335', 'Hook Up Diagram', 'Installation details.', NULL, NULL, 'MX', 'Mechanical Other', 'AFC, AFU, AFD', 415),
('2343', 'Isometric Diagram', 'A three dimensional representation of an object.', 'Tier 2', 'RLMU', 'MX', 'Mechanical Other', 'ASB, AFC, AFU, AFD', 416),
('2358', 'Support Diagram', 'Piping support, pipe rack.', NULL, NULL, 'MX', 'Mechanical Other', 'AFC, AFU, AFD', 417),
('2368', 'Process Safeguarding Flow Scheme', 'Shows all process safeguarding and relief devices.', 'Tier 1', 'RLMU', 'MX', 'Mechanical Other', 'ASB, AFC, AFU, AFD', 418),
('3309', 'Bill Of Quantities', 'A list of whole assemblies or bulk material.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 419),
('3323', 'Technical Note', 'Agreement which describes how an issue will be resolved.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 420),
('3328', 'Installation Manual', 'Installation refers to the mounting, setting, erection.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 421),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 422),
('3366', 'Technical Query', 'Technical Query Includes STQ', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 423),
('3375', 'Work Instruction', 'Self Explanatory', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 424),
('4024', 'Layout Diagram, Plot Plan', 'Plan view of a area showing exact location.', NULL, NULL, 'MX', 'Mechanical Other', 'ASB, AFC, AFU, AFD', 425),
('4033', 'Piping Layout Diagram', 'Shows the precise location of piping and ducting.', NULL, NULL, 'MX', 'Mechanical Other', 'ASB, AFC, AFU, AFD', 426),
('4180', 'Other Layout Diagram', NULL, NULL, NULL, 'MX', 'Mechanical Other', 'AFC, AFU, AFD', 427),
('4306', 'Bill of Materials', 'A list of all parts, sub assemblies and raw materials.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 428),
('4354', 'Spare Part List', 'Recommended listing of spares.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 429),
('4380', 'Other List', NULL, NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 430),
('4816', 'Method Statement', NULL, NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 431),
('5280', 'Other Multimedia', NULL, NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 432),
('5507', 'Design Philosophy', 'A set of ideas, beliefs, or underlying theory.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 433),
('5525', 'Piping Design Philosophy', NULL, NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 434),
('5680', 'Other Philosophy', NULL, NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 435),
('5880', 'Other Plan', NULL, NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 436),
('6067', 'Acceptance Test Procedure', 'Includes FAT and non-FAT procedures.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 437),
('6180', 'Other Procedure', NULL, NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 438),
('6612', 'Equipment Register', 'Master Tag and Equipment list.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 439),
('7180', 'Other Report', NULL, NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 440),
('7205', 'Technical Deviation Request', 'Request, approval or rejection of changes.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 441),
('7303', 'Requisition', 'A request for service or product.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 442),
('7739', 'Project Specification', 'A technical description of the information on a Project.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 443),
('7753', 'Terms Of Reference', 'Specifies the scope and details of the activity.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 444),
('7770', 'Other Functional Design Specification', 'Specification that describes the deliverable.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 445),
('7771', 'Equipment Specification', 'Gives precise information about a Tag.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 446),
('7880', 'Other Specification', NULL, NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 447),
('8218', 'Design Layout Study', 'A work that results from studious endeavour.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 448),
('8380', 'Other Study', NULL, NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 449),
('8502', 'Clarification Request', 'Clarification RFI at the start of contract.', NULL, NULL, 'MX', 'Mechanical Other', 'IFI, AFU, AFP, AFT', 450),
-- OA Operations
('780', 'Other Assessment Report', 'Health check, GAP analysis etc.', NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 451),
('2105', 'Equipment Datasheet', 'Gives precise information about a Tag.', NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 452),
('3323', 'Technical Note', 'Agreement which describes how an issue will be resolved.', NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 453),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 454),
('3366', 'Technical Query', 'Technical Query Includes STQ', NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 455),
('3375', 'Work Instruction', 'Self Explanatory', NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 456),
('4354', 'Spare Part List', 'Recommended listing of spares.', NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 457),
('4810', 'Operating Manual', 'Operating guidelines and instructions.', 'Tier 1', 'RLMU', 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 458),
('4811', 'Maintenance Manual', 'Maintenance instructions for equipment.', 'Tier 1', 'RLMU', 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 459),
('4880', 'Other Manual', 'A document that describes methods of working.', NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 460),
('5160', 'Forms & Templates', NULL, NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 461),
('5280', 'Other Multimedia', NULL, NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 462),
('5521', 'Operations Philosophy', 'Including start-up/shutdown.', NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 463),
('5680', 'Other Philosophy', NULL, NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 464),
('5877', 'Flawless Project Delivery Plan', 'An overall plan explaining how FPD is implemented.', NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 465),
('5880', 'Other Plan', NULL, NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 466),
('5980', 'Other Strategy', NULL, NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 467),
('6039', 'Operating Procedure', 'Supervisory Level Operating Procedures.', 'Tier 1', 'RLMU', 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 468),
('6180', 'Other Procedure', NULL, NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 469),
('6680', 'Other Register', NULL, NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 470),
('7180', 'Other Report', NULL, NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 471),
('7739', 'Project Specification', 'A technical description of the information on a Project.', NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 472),
('7753', 'Terms Of Reference', 'Specifies the scope and details of the activity.', NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 473),
('7880', 'Other Specification', NULL, NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 474),
('8380', 'Other Study', NULL, NULL, NULL, 'OA', 'Operations', 'IFI, AFU, AFP, AFT', 475),
-- PX Process Other
('504', 'Fluid Analysis Report', 'Details the composition/makeup of process and produced fluids.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 476),
('580', 'Other Analysis Report', NULL, NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 477),
('902', 'Facility Block Diagram', 'For Process, High Level Process Flow Diagram.', NULL, NULL, 'PX', 'Process Other', 'ASB, AFC, AFU, AFD', 478),
('1206', 'Design Calculation', 'Design calculations.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 479),
('1216', 'Heat and Mass Balance Calculation', 'Process simulation and process calculations.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 480),
('1380', 'Other Calculation', NULL, NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 481),
('1979', 'Database and Data set', 'Data stored in a proprietary or neutral format.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 482),
('2105', 'Equipment Datasheet', 'Gives precise information about a Tag.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 483),
('2336', 'Hydraulic, Pneumatic Diagram', 'Schematics for any system not covered by PEFS/UEFS.', NULL, NULL, 'PX', 'Process Other', 'AFC, AFU, AFD', 484),
('2341', 'Interface Diagram', 'Diagrams showing Interface between Contractors.', NULL, NULL, 'PX', 'Process Other', 'AFC, AFU, AFD', 485),
('2366', 'Process Flow Scheme', 'Details major items of equipment, primary lines and valves.', NULL, NULL, 'PX', 'Process Other', 'ASB, AFC, AFU, AFD', 486),
('2908', 'Relief Valve Calculation', 'Process Relief Valve calculation.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 487),
('3323', 'Technical Note', 'Agreement which describes how an issue will be resolved.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 488),
('3329', 'Integrity Operating Envelope', 'Specifies the lower and upper safe working operating parameters.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 489),
('3342', 'Heat and Mass Balance Summary', 'Chart summarising mass flow rates at key points.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 490),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 491),
('3363', 'Safeguarding Memorandum', 'The memorandum describes required process relief cases.', 'Tier 1', NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 492),
('3366', 'Technical Query', 'Technical Query Includes STQ', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 493),
('4322', 'Equipment Summary List', 'An extract from a Register.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 494),
('4363', 'Tie-In List', 'Tie-In includes interfaces between project stages.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 495),
('4603', 'Hydraulic Calculation', 'Calculations for equipment sizing.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 496),
('4814', 'Process Manual', 'Defines the process design and operations requirement.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 497),
('5507', 'Design Philosophy', 'A set of ideas, beliefs, or underlying theory.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 498),
('5517', 'Isolation Philosophy', NULL, NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 499),
('5520', 'Metering Philosophy', 'Documentation of the metering and allocation philosophy.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 500),
('5527', 'Process Description Philosophy', NULL, NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 501),
('5680', 'Other Philosophy', NULL, NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 502),
('5721', 'Engineering Design Strategy', NULL, NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 503),
('5743', 'Material Selection Plan', NULL, NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 504),
('5880', 'Other Plan', NULL, NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 505),
('6067', 'Acceptance Test Procedure', 'Includes FAT and non-FAT procedures.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 506),
('6180', 'Other Procedure', NULL, NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 507),
('6204', 'Process, Utility Calculation', 'Process related calculations.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 508),
('6612', 'Equipment Register', 'Master Tag and Equipment list.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 509),
('7180', 'Other Report', NULL, NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 510),
('7205', 'Technical Deviation Request', 'Request, approval or rejection of changes.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 511),
('7403', 'Design Review Report', 'Verification of a design.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 512),
('7739', 'Project Specification', 'A technical description of the information on a Project.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 513),
('7741', 'Relief, Blowdown Specification', 'Sizing data for the relief and blowdown systems.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 514),
('7753', 'Terms Of Reference', 'Specifies the scope and details of the activity.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 515),
('7770', 'Other Functional Design Specification', 'Specification that describes the deliverable.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 516),
('7880', 'Other Specification', NULL, NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 517),
('8240', 'Design Cases Study', 'Defines the process design cases.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 518),
('8248', 'Process Control, Optimisation Study', 'Specific process control studies.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 519),
('8380', 'Other Study', NULL, NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 520),
('8502', 'Clarification Request', 'Clarification RFI at the start of contract.', NULL, NULL, 'PX', 'Process Other', 'IFI, AFU, AFP, AFT', 521),
-- QA Quality Assurance
('880', 'Other Audit Report', 'Independent assurances of compliance.', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 522),
('1426', 'Material Test Certificate', NULL, NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 523),
('1580', 'Other Certificate', NULL, NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 524),
('3323', 'Technical Note', 'Agreement which describes how an issue will be resolved.', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 525),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 526),
('3366', 'Technical Query', 'Technical Query Includes STQ', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 527),
('3375', 'Work Instruction', 'Self Explanatory', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 528),
('3880', 'Other Inspection Report', 'Summary of physical verification of conformance.', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 529),
('4815', 'Quality Manual', 'Quality Management System.', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 530),
('4816', 'Method Statement', NULL, NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 531),
('5160', 'Forms & Templates', NULL, NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 532),
('5707', 'Audit Plan', 'Schedule or plan for carrying out project quality audits', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 533),
('5733', 'Inspection Plan', 'Inspection and test plan for all construction work', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 534),
('5798', 'Project Plan', 'Reserved for project wide Discipline Management Plans.', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 535),
('5880', 'Other Plan', NULL, NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 536),
('6050', 'Quality Procedure', 'Quality management procedure.', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 537),
('6180', 'Other Procedure', NULL, NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 538),
('6830', 'Corrective Action Report', 'Details of actions to be taken to remedy a finding.', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 539),
('6876', 'Health Check Report', 'About business process health.', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 540),
('6918', 'Non Conformance Report', 'A condition where characteristics do not conform to requirements.', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 541),
('6950', 'Quality Report', 'Summary of any investigation.', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 542),
('7180', 'Other Report', NULL, NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 543),
('7403', 'Design Review Report', 'Verification of a design.', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 544),
('7480', 'Other Review Report', NULL, NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 545),
('7739', 'Project Specification', 'A technical description of the information on a Project.', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 546),
('7753', 'Terms Of Reference', 'Specifies the scope and details of the activity.', NULL, NULL, 'QA', 'Quality Assurance', 'IFI, AFU, AFP, AFT', 547),
-- RA Materials and Corrosion
('709', 'Risk Assessment Report', 'Overall assessment of risk.', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 548),
('1206', 'Design Calculation', 'Prepared in order to prove that the item meets criteria.', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 549),
('1580', 'Other Certificate', NULL, NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 550),
('2105', 'Equipment Datasheet', 'Gives precise information about a Tag.', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 551),
('2309', 'Cathodic Protection Diagram', 'Showing locations of cathodic protection.', NULL, NULL, 'RA', 'Materials and Corrosion', 'AFC, AFU, AFD', 552),
('2349', 'Material Selection Diagram', 'Describes materials and reasons for selecting those materials.', NULL, NULL, 'RA', 'Materials and Corrosion', 'AFC, AFU, AFD', 553),
('3323', 'Technical Note', 'Agreement which describes how an issue will be resolved.', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 554),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 555),
('3366', 'Technical Query', 'Technical Query Includes STQ', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 556),
('3375', 'Work Instruction', 'Step by Step instruction.', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 557),
('4816', 'Method Statement', NULL, NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 558),
('4880', 'Other Manual', 'Quality Management System.', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 559),
('5519', 'Corrosion Philosophy', 'Outlines the design rules and principles relating to corrosion.', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 560),
('5680', 'Other Philosophy', NULL, NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 561),
('5770', 'Corrosion Inhibition Testing Plan', 'Corrosion inhibitor testing requirements.', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 562),
('5779', 'Material Testing Plan', 'Material testing covering mechanical or corrosion testing.', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 563),
('6038', 'Non Destructive Test Procedure', 'Includes all non-destructive tests/examinations.', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 564),
('6180', 'Other Procedure', NULL, NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 565),
('7180', 'Other Report', NULL, NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 566),
('7205', 'Technical Deviation Request', 'Request, approval or rejection of changes.', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 567),
('7303', 'Requisition', 'A request for service or product.', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 568),
('7739', 'Project Specification', 'A technical description of the information on a Project.', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 569),
('7753', 'Terms Of Reference', 'Specifies the scope and details of the activity.', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 570),
('7880', 'Other Specification', NULL, NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 571),
('8380', 'Other Study', NULL, NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 572),
('8502', 'Clarification Request', 'Clarification RFI at the start of contract.', NULL, NULL, 'RA', 'Materials and Corrosion', 'IFI, AFU, AFP, AFT', 573),
-- TA Telecom
('602', 'Equipment Location Diagram', 'Shows the physical location of all equipment.', NULL, NULL, 'TA', 'Telecom', 'ASB, AFC, AFU, AFD', 574),
('901', 'Single Line Diagram', 'A simplified notation for representing a system.', 'Tier 2', 'RLMU', 'TA', 'Telecom', 'ASB, AFC, AFU, AFD', 575),
('980', 'Other Block Diagram', 'A pictorial representation of a process.', NULL, NULL, 'TA', 'Telecom', 'AFC, AFU, AFD', 576),
('2105', 'Equipment Datasheet', 'Gives precise information about a Tag.', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 577),
('2305', 'Assembly Diagram', 'Shows an assembly of equipment components.', NULL, NULL, 'TA', 'Telecom', 'AFC, AFU, AFD', 578),
('2335', 'Hook Up Diagram', 'Installation details.', NULL, NULL, 'TA', 'Telecom', 'AFC, AFU, AFD', 579),
('2341', 'Interface Diagram', 'Diagrams showing Interface.', NULL, NULL, 'TA', 'Telecom', 'AFC, AFU, AFD', 580),
('2373', 'Routing Diagram', 'Alignment of cables and pipelines.', NULL, NULL, 'TA', 'Telecom', 'ASB, AFC, AFU, AFD', 581),
('3309', 'Bill Of Quantities', 'A list of whole assemblies.', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 582),
('3323', 'Technical Note', 'Agreement which describes how an issue will be resolved.', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 583),
('3328', 'Installation Manual', 'Installation refers to the mounting, setting, erection.', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 584),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 585),
('3366', 'Technical Query', 'Technical Query Includes STQ', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 586),
('4005', 'Cable Tray Layout Diagram', NULL, NULL, NULL, 'TA', 'Telecom', 'AFC, AFU, AFD', 587),
('4013', 'Field Auxiliary Room Layout Diagram', NULL, 'Tier 2', 'RLMU', 'TA', 'Telecom', 'AFC, AFU, AFD', 588),
('4024', 'Layout Diagram, Plot Plan', 'Plan view of a area showing exact location.', NULL, NULL, 'TA', 'Telecom', 'ASB, AFC, AFU, AFD', 589),
('4306', 'Bill of Materials', 'A list of all parts.', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 590),
('4308', 'Cable List', 'List of all cables, their specifications and end points.', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 591),
('5507', 'Design Philosophy', 'A set of ideas, beliefs, or underlying theory.', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 592),
('5680', 'Other Philosophy', NULL, NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 593),
('5880', 'Other Plan', NULL, NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 594),
('6067', 'Acceptance Test Procedure', 'Includes FAT and non-FAT procedures.', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 595),
('6180', 'Other Procedure', NULL, NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 596),
('6612', 'Equipment Register', 'Master Tag and Equipment list.', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 597),
('7180', 'Other Report', NULL, NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 598),
('7205', 'Technical Deviation Request', 'Request, approval or rejection.', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 599),
('7303', 'Requisition', 'A request for service or product.', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 600),
('7731', 'Network Architecture Specification', NULL, NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 601),
('7739', 'Project Specification', 'A technical description.', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 602),
('7753', 'Terms Of Reference', 'Specifies the scope and details.', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 603),
('7771', 'Equipment Specification', 'Gives precise information.', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 604),
('7880', 'Other Specification', NULL, NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 605),
('8380', 'Other Study', NULL, NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 606),
('8502', 'Clarification Request', 'Clarification RFI at the start of contract.', NULL, NULL, 'TA', 'Telecom', 'IFI, AFU, AFP, AFT', 607),
('8804', 'Connection Diagram', 'Details of cable numbers and terminations.', NULL, NULL, 'TA', 'Telecom', 'AFC, AFU, AFD', 608),
('8880', 'Other Wiring Diagram', NULL, NULL, NULL, 'TA', 'Telecom', 'AFC, AFU, AFD', 609),
-- ZV Vendor Documentation (representative sample)
('A01', 'Certified Vendor Diagram', 'A certified drawing or diagram from the vendor.', NULL, NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 610),
('A02', 'Outline / General Arrangement Diagram', 'Overall dimensions and arrangements.', NULL, NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 611),
('A03', 'Cross Section Diagram', NULL, NULL, NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 612),
('B01', 'Piping and Instrument Diagram', 'Process and instrument diagram.', 'Tier 1', NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 613),
('C01', 'Equipment Datasheet', 'Process, Mechanical, Electrical, Instrumentation datasheets.', NULL, NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 614),
('D01', 'Process Flow Diagram', NULL, NULL, NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 615),
('D02', 'Process Engineering Flow Scheme', 'P&ID', 'Tier 1', NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 616),
('E01', 'Electrical Schematic', NULL, NULL, NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 617),
('E02', 'Electrical Single Line Diagram', NULL, 'Tier 1', NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 618),
('F01', 'Design Calculation', NULL, NULL, NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 619),
('G01', 'Erection and Installation Procedure', 'Lifting points, weights, procedures.', NULL, NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 620),
('H01', 'Quality Manual', 'ISO 9000 approved quality system.', NULL, NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 621),
('H02', 'Inspection and Test Plan / Quality Plan', 'ITP with hold and witness points.', NULL, NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 622),
('J01', 'Operating and Maintenance Manual', 'Description of equipment, operating procedures.', 'Tier 2', NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 623),
('K01', 'Certification Manufacturing Data Book', 'Comprehensive indexed volume.', NULL, NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 624),
('K05', 'Factory Acceptance Test Report (FAT)', 'Report on performance/functional tests.', 'Tier 2', NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 625),
('L01', 'Material Test Certificate', 'Certificates in compliance with standards.', NULL, NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 626),
('M01', 'Packing and Shipping Schedule', 'Schedule identifying all major components.', NULL, NULL, 'ZV', 'Vendor Documentation', 'IFI, AFU, AFP, AFT', 627),
-- JA Information Management
('1400', 'Handover Packages (Document and Data)', 'Register/Listing of Handover Package Contents', NULL, NULL, 'JA', 'Information Management', 'IFI, AFU, AFP, AFT', 628),
('1780', 'Correspondence', 'Any form of written communication.', NULL, NULL, 'JA', 'Information Management', 'IFI, AFU, AFP, AFT', 629),
('1979', 'Database and Data set', 'Data stored in a proprietary or neutral format.', NULL, NULL, 'JA', 'Information Management', 'IFI, AFU, AFP, AFT', 630),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'JA', 'Information Management', 'IFI, AFU, AFP, AFT', 631),
('3357', 'Presentation', 'General Presentation material.', NULL, NULL, 'JA', 'Information Management', 'IFI, AFU, AFP, AFT', 632),
('3366', 'Technical Query', 'Technical Query Includes STQ', NULL, NULL, 'JA', 'Information Management', 'IFI, AFU, AFP, AFT', 633),
('4372', 'Index of Documents', 'Books require this Index to be created.', NULL, NULL, 'JA', 'Information Management', 'IFI, AFU, AFP, AFT', 634),
('5762', 'Project Lifecycle Information Plan', 'Plan listing all information types.', NULL, NULL, 'JA', 'Information Management', 'IFI, AFU, AFP, AFT', 635),
('5798', 'Project Plan', 'Reserved for project wide Discipline Management Plans.', NULL, NULL, 'JA', 'Information Management', 'IFI, AFU, AFP, AFT', 636),
('6017', 'Document, Data Control Procedure', 'Procedures specifically for document and data control.', NULL, NULL, 'JA', 'Information Management', 'IFI, AFU, AFP, AFT', 637),
('6610', 'Document Distribution Matrix', 'An overview of distribution process for documents.', NULL, NULL, 'JA', 'Information Management', 'IFI, AFU, AFP, AFT', 638),
('6611', 'Document, Data Register', 'Register of the documents and data delivered.', NULL, NULL, 'JA', 'Information Management', 'IFI, AFU, AFP, AFT', 639),
('7712', 'Document Type Requirement Specification', 'Specification of Information types required.', NULL, NULL, 'JA', 'Information Management', 'IFI, AFU, AFP, AFT', 640),
('7739', 'Project Specification', 'A technical description.', NULL, NULL, 'JA', 'Information Management', 'IFI, AFU, AFP, AFT', 641),
('7753', 'Terms Of Reference', 'Specifies the scope and details.', NULL, NULL, 'JA', 'Information Management', 'IFI, AFU, AFP, AFT', 642),
-- KA Information Technology
('3304', 'Application software', 'A computer program designed for a specific task.', NULL, NULL, 'KA', 'Information Technology', 'IFI, AFU, AFP, AFT', 643),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'KA', 'Information Technology', 'IFI, AFU, AFP, AFT', 644),
('7739', 'Project Specification', 'A technical description.', NULL, NULL, 'KA', 'Information Technology', 'IFI, AFU, AFP, AFT', 645),
('7753', 'Terms Of Reference', 'Specifies the scope and details.', NULL, NULL, 'KA', 'Information Technology', 'IFI, AFU, AFP, AFT', 646),
('8502', 'Clarification Request', 'Clarification RFI at the start of contract.', NULL, NULL, 'KA', 'Information Technology', 'IFI, AFU, AFP, AFT', 647),
-- VA Contracting and Procurement
('403', 'Contract', NULL, NULL, NULL, 'VA', 'Contracting and Procurement', 'IFI, AFU, AFP, AFT', 648),
('1701', 'Award Letter', NULL, NULL, NULL, 'VA', 'Contracting and Procurement', 'IFI, AFU, AFP, AFT', 649),
('3330', 'Invitation To Tender', 'A standardised document for inviting Tenderers.', NULL, NULL, 'VA', 'Contracting and Procurement', 'IFI, AFU, AFP, AFT', 650),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'VA', 'Contracting and Procurement', 'IFI, AFU, AFP, AFT', 651),
('3359', 'Purchase Order', NULL, NULL, NULL, 'VA', 'Contracting and Procurement', 'IFI, AFU, AFP, AFT', 652),
('3369', 'Variation Order', 'Variation Orders issued against existing Contracts.', NULL, NULL, 'VA', 'Contracting and Procurement', 'IFI, AFU, AFP, AFT', 653),
('4305', 'Approved Vendor List', 'List Approved for a particular contract.', NULL, NULL, 'VA', 'Contracting and Procurement', 'IFI, AFU, AFP, AFT', 654),
('5756', 'Procurement, Contracting Strategy', 'The purpose of developing contracting and procurement strategies.', NULL, NULL, 'VA', 'Contracting and Procurement', 'IFI, AFU, AFP, AFT', 655),
('5793', 'Scope Of Work', 'Definition of work to be performed.', NULL, NULL, 'VA', 'Contracting and Procurement', 'IFI, AFU, AFP, AFT', 656),
('6047', 'Procurement Plan', 'Plan for the purchase of bulk materials.', NULL, NULL, 'VA', 'Contracting and Procurement', 'IFI, AFU, AFP, AFT', 657),
('6999', 'Tender Evaluation', 'Technical or Commercial evaluation of tender.', NULL, NULL, 'VA', 'Contracting and Procurement', 'IFI, AFU, AFP, AFT', 658),
('7206', 'Variation Request', 'A request for changes to an existing contract.', NULL, NULL, 'VA', 'Contracting and Procurement', 'IFI, AFU, AFP, AFT', 659),
('7303', 'Requisition', 'A request for service or product.', NULL, NULL, 'VA', 'Contracting and Procurement', 'IFI, AFU, AFP, AFT', 660),
('7739', 'Project Specification', 'A technical description.', NULL, NULL, 'VA', 'Contracting and Procurement', 'IFI, AFU, AFP, AFT', 661),
('8502', 'Clarification Request', 'Clarification RFI at the start of contract.', NULL, NULL, 'VA', 'Contracting and Procurement', 'IFI, AFU, AFP, AFT', 662),
-- FA Cost and Planning
('709', 'Risk Assessment Report', 'Overall assessment of risk.', NULL, NULL, 'FA', 'Cost and Planning', 'IFI, AFU, AFP, AFT', 663),
('3101', 'Cost Estimate', 'Cost estimate for any type of activity.', NULL, NULL, 'FA', 'Cost and Planning', 'IFI, AFU, AFP, AFT', 664),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'FA', 'Cost and Planning', 'IFI, AFU, AFP, AFT', 665),
('5722', 'Engineering Schedule', 'Includes Engineering and Design.', NULL, NULL, 'FA', 'Cost and Planning', 'IFI, AFU, AFP, AFT', 666),
('5765', 'Project Schedule', 'Includes Project Wide Management.', NULL, NULL, 'FA', 'Cost and Planning', 'IFI, AFU, AFP, AFT', 667),
('5792', 'Work Breakdown Structure Plan', 'Defining scope of work into smaller manageable blocks.', NULL, NULL, 'FA', 'Cost and Planning', 'IFI, AFU, AFP, AFT', 668),
('5802', 'Construction Schedule', 'Construct is to Erect, Build, or Make on-site.', NULL, NULL, 'FA', 'Cost and Planning', 'IFI, AFU, AFP, AFT', 669),
('5803', 'Fabrication Schedule', 'Fabricate is to Manufacture off-site.', NULL, NULL, 'FA', 'Cost and Planning', 'IFI, AFU, AFP, AFT', 670),
('6015', 'Cost Control Procedure', 'Procedures for monitoring, controlling expenditures.', NULL, NULL, 'FA', 'Cost and Planning', 'IFI, AFU, AFP, AFT', 671),
('6044', 'Planning Procedure', 'Procedures for planning the project.', NULL, NULL, 'FA', 'Cost and Planning', 'IFI, AFU, AFP, AFT', 672),
('6401', 'Budget Proposal', 'Distribution of funds within a Project.', NULL, NULL, 'FA', 'Cost and Planning', 'IFI, AFU, AFP, AFT', 673),
('6833', 'Cost Report', 'Financial progress report.', NULL, NULL, 'FA', 'Cost and Planning', 'IFI, AFU, AFP, AFT', 674),
('6834', 'Cost Time Resource Estimate Report', 'Estimate of resources required.', NULL, NULL, 'FA', 'Cost and Planning', 'IFI, AFU, AFP, AFT', 675),
('7753', 'Terms Of Reference', 'Specifies the scope and details.', NULL, NULL, 'FA', 'Cost and Planning', 'IFI, AFU, AFP, AFT', 676),
-- ZF Finance
('1003', 'Corporate Authority For Expenditure', 'Investment Proposal to allocate funds.', NULL, NULL, 'ZF', 'Finance', 'IFI, AFU, AFP, AFT', 677),
('3905', 'Invoice', 'Document showing charges for goods delivered.', NULL, NULL, 'ZF', 'Finance', 'IFI, AFU, AFP, AFT', 678),
-- ZH Human Resources
('1449', 'Welder Qualification Certificate', NULL, NULL, NULL, 'ZH', 'Human Resources', 'IFI, AFU, AFP, AFT', 679),
('3377', 'Job Description', 'Describes required skill, knowledge, experience.', NULL, NULL, 'ZH', 'Human Resources', 'IFI, AFU, AFP, AFT', 680),
-- UA Subsea
('780', 'Other Assessment Report', 'Health check, GAP analysis etc.', NULL, NULL, 'UA', 'Subsea', 'IFI, AFU, AFP, AFT', 681),
('2105', 'Equipment Datasheet', 'Gives precise information about a Tag.', NULL, NULL, 'UA', 'Subsea', 'IFI, AFU, AFP, AFT', 682),
('4018', 'General Arrangement Diagram', 'A diagram showing the main features and locations.', 'Tier 1', 'RLMU', 'UA', 'Subsea', 'AFC, AFU, AFD', 683),
('7303', 'Requisition', 'A request for service or product.', NULL, NULL, 'UA', 'Subsea', 'IFI, AFU, AFP, AFT', 684),
('7739', 'Project Specification', 'A technical description.', NULL, NULL, 'UA', 'Subsea', 'IFI, AFU, AFP, AFT', 685),
('7771', 'Equipment Specification', 'Gives precise information.', NULL, NULL, 'UA', 'Subsea', 'IFI, AFU, AFP, AFT', 686),
-- ZW Well Engineering
('5720', 'Drilling Plan', 'Typically includes a list of wells.', NULL, NULL, 'ZW', 'Well Engineering', 'IFI, AFU, AFP, AFT', 687),
('5980', 'Other Strategy', NULL, NULL, NULL, 'ZW', 'Well Engineering', 'IFI, AFU, AFP, AFT', 688),
('6409', 'Well Proposal', 'Advice to the company for drilling.', NULL, NULL, 'ZW', 'Well Engineering', 'IFI, AFU, AFP, AFT', 689),
('7180', 'Other Report', NULL, NULL, NULL, 'ZW', 'Well Engineering', 'IFI, AFU, AFP, AFT', 690),
-- Remaining misc disciplines
('7180', 'Other Report', NULL, NULL, NULL, 'ZP', 'Petrophysics', 'IFI, AFU, AFP, AFT', 691),
('8380', 'Other Study', NULL, NULL, NULL, 'ZP', 'Petrophysics', 'IFI, AFU, AFP, AFT', 692),
('7180', 'Other Report', NULL, NULL, NULL, 'ZR', 'Reservoir Engineering', 'IFI, AFU, AFP, AFT', 693),
('8380', 'Other Study', NULL, NULL, NULL, 'ZR', 'Reservoir Engineering', 'IFI, AFU, AFP, AFT', 694),
('7180', 'Other Report', NULL, NULL, NULL, 'ZS', 'Geophysics', 'IFI, AFU, AFP, AFT', 695),
('8380', 'Other Study', NULL, NULL, NULL, 'ZS', 'Geophysics', 'IFI, AFU, AFP, AFT', 696),
('3347', 'Minutes Of Meeting', 'Minutes of meetings between client and contractor', NULL, NULL, 'ZT', 'Production Technology', 'IFI, AFU, AFP, AFT', 697),
('7180', 'Other Report', NULL, NULL, NULL, 'ZT', 'Production Technology', 'IFI, AFU, AFP, AFT', 698),
('8380', 'Other Study', NULL, NULL, NULL, 'ZT', 'Production Technology', 'IFI, AFU, AFP, AFT', 699);
